### ISSUE TITLE
About page does not show that you are logged in or have a way to go home.

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#103]
The title explains it.

**Comment by willweinstein** [comment]
Hi

**Comment by willweinstein** [comment]
@nywillb AM I ALLOWED TO EDIT CODE? THE NO WAY TO GET HOME THINGY IS EASY TO FIX

**Comment by willweinstein** [comment]
@nywillb AND MY AM I ALLOWED TO EDIT CODE, I MEAN IT SAYS I DON'T HAVE PERMISSION, PLS GIVE ME PERMISSION

**Comment by medensqui** [comment]
sup

**Comment by medensqui** [comment]
@willweinstein THAT WAS SEHAN

**Comment by thatoddmailbox** [comment]
@willweinstein FORK IT A MAKE A PULL REQUEST

**Comment by thatoddmailbox** [comment]
@willweinstein OR DON'T BECAUSE I FIXED IT
