### ISSUE TITLE
BUGS THAT I HAVE NOTICED

### ISSUE THREAD

**Issue by willweinstein** [PlanHubMe/PlanHub#104]
1. Two of my rows are glitched... (it says objects are in language and science when they are in science and blah) (language has something but it is hidden) (hw view displays the correct stuff but planner doesn't)
2. ONE ROW STOPPED BEING REGISTERED IN HW VIEW
3. MY NAME IS WILL NOT WILLIAM I WANNA CHANGE IT
4. DOESN'T LOG YOU OUT WHEN YOU CLOSE THE PAGE
5. BUGS 1 AND 2 FIXED BY DELETING ROWS AND PUTTING THEM BACK IN ARGHHHHHHHHHHH

**Comment by medensqui** [comment]
@willweinstein ITS IN BETA FOR GODS SAKE

**Comment by thatoddmailbox** [comment]
@willweinstein 

> Two of my rows are glitched... (it says objects are in language and science when they are in science and blah) (language has something but it is hidden) (hw view displays the correct stuff but planner doesn't)

! What do you mean? When you write something in one row and reload, it appears in another?

> ONE ROW STOPPED BEING REGISTERED IN HW VIEW

Is it the same as one of the rows affected by the above glitch?

> MY NAME IS WILL NOT WILLIAM I WANNA CHANGE IT

OK GEEZ WE CAN MAKE A PROFILE PAGE OR SOMETHING BUT NOT NOW

> DOESN'T LOG YOU OUT WHEN YOU CLOSE THE PAGE

It doesn't? Are you closing the browser window or just the tab?

> BUGS 1 AND 2 FIXED BY DELETING ROWS AND PUTTING THEM BACK IN ARGHHHHHHHHHHH

That's weird...

**Comment by thatoddmailbox** [comment]
@willweinstein Are these still happening? Some fixes were recently made to HW View that may have solved some or all of these bugs.

**Comment by willweinstein** [comment]
@thatoddmailbox they happened once and never again so i have no idea. don't know how they happened but they did

**Comment by willweinstein** [comment]
@thatoddmailbox 
1.  exactly but just the display. it still listed them correctly in hw view
1. no my hex row just wasn't showing its assignments in hw view it was not one of the glitched views
2. PROFILE PAGE
3. CLOSING THE WINDOW

**Comment by willweinstein** [comment]
@thatoddmailbox another bug is the url is planhub.me for some reason instead of studerplanner.tk

**Comment by thatoddmailbox** [comment]
@willweinstein I fixed that bug. studerplanner.tk, studerplanner.gq, studerplanner.cf, studerplanner.ga, and studerplanner.ml all redirect to planhub.me 
1. That is weird... I can look at it in bio today
2. Is that still happening?
3. BUT NOT NOW BC WE HAVE A DEADLINE
4. WELL THEN THAT IS WEIRD MAYBE THE COOKIE ISN'T ON SESSION MODE BUT TOO BAD THAT WON'T BE FIXED TODAY BECAUSE DEADLINE AAAAGH

**Comment by medensqui** [comment]
@thatoddmailbox HAHAHAHAHAHA

**Comment by willweinstein** [comment]
@thatoddmailbox why do we have a deadline again?

**Comment by thatoddmailbox** [comment]
@willweinstein So we don't just keep going "oh no, it could be better, let's not make it public", we tell everyone the deadline.

**Comment by willweinstein** [comment]
@thatoddmailbox it seems a bit soon though

**Comment by willweinstein** [comment]
@thatoddmailbox something is definitely off with the cookie because i just opened studerplanner.tk for the first time and I WAS LOGGED IN
