### ISSUE TITLE
Front page could be better

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#11]
This is a while away but some ideas
- A tour?
- About page
- Link to repository
- Features
- Screenshots

**Comment by thatoddmailbox** [comment]
@medensqui
Ideas for features
- something about homework always being with you
- something about being clear and at-a-glance
- something about making life easier?
- ...

**Comment by medensqui** [comment]
@thatoddmailbox More like 
- Schedule
- My Day
- HW View
- Planner

**Comment by thatoddmailbox** [comment]
@medensqui Maybe have what I said at the top like:
| bla bla | bla bla | bla bla |
format and then do a breakdown of each feature.

**Comment by thatoddmailbox** [comment]
@medensqui I added more words to the front page, but someone has to take some screenshots...

**Comment by thatoddmailbox** [comment]
@medensqui I added everything on that list but a tour and screenshots.

I will close this now, as I don't think those are things that have to be done by the initial release.
