### ISSUE TITLE
Clicking "get started" on homepage while logged in still opens login page

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#12]
It should lead you to the Overview screen if you are already logged in.

**Comment by medensqui** [comment]
@thatoddmailbox That should be simple right? With a simple if script
aka

If Logged in link here
else link here

**Comment by thatoddmailbox** [comment]
@medensqui Yes, but I am too lazy to do it now, yet I didn't want to forget.

So, I made this issue.
