### ISSUE TITLE
Email beta testers

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#125]
When PlanHub is fully open, we should send a thank-you email to everyone who participated in the beta. This tells them:
a. thank you
b. intermittent bugginess and major issues have been solved now because _obviously_ we'd start using a staging environment then
c. other people can use it now, go tell your friends

**Comment by thatoddmailbox** [comment]
I'm not sure if this should go on the milestone or not...

**Comment by medensqui** [comment]
@thatoddmailbox Nope but still needed

**Comment by thatoddmailbox** [comment]
@medensqui @nywillb @willweinstein YAY I MADE A GDOC FOR THIS

**Comment by willbarkoff** [comment]
Closing... This is not needed
