### ISSUE TITLE
Why can't I edit code

### ISSUE THREAD

**Issue by willweinstein** [PlanHubMe/PlanHub#126]
i wanna edit stuffs

**Comment by thatoddmailbox** [comment]
@willweinstein FINE BUT HERE ARE THE RULES:
- Don't push to stable
- Do not push to stable
- Stable is not where you will push to
- Merge from master to stable&mdash;do not push to stable

**Comment by thatoddmailbox** [comment]
@willweinstein ACCEPT THE INVITE
