### ISSUE TITLE
Memory Leaks

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#127]
There seems to be a significant amount of leaking memory on every request&mdash;even on requests to the home page! Anywhere from 0.5 to 2 MB.

This has to be resolved before subjecting it to public load.

**Comment by willweinstein** [comment]
@thatoddmailbox DDoS time!!!

**Comment by thatoddmailbox** [comment]
@willweinstein No.

**Comment by thatoddmailbox** [comment]
I'm not sure which is better: do some aggressive restart/RAM settings on the server to make the memory leaks not a problem, or to look at it under the microscope of my desktop computer, which I probably can't do until Friday.

**Comment by thatoddmailbox** [comment]
paging @nywillb @medensqui

**Comment by medensqui** [comment]
@thatoddmailbox AGGRESSIVE SETTINGS WE CANT DELAY UNTIL FRIDAY

**Comment by willweinstein** [comment]
@thatoddmailbox WHY NOT SEND IT TO A GROP OF HAKRS THEY R FRIENDLY

**Comment by thatoddmailbox** [comment]
@willweinstein @medensqui 
I'm actually not sure if there are memory leaks. (leave this issue open though) The increasing memory usage may have been Node trying its best on the tiny slice of the 768 MBs of RAM the server had.

Now I've moved it to its own server and ~~DDoSed~~ load tested it with 250 users over one minute (loading the home page). The CPU spiked up, but the memory usage stayed the same....

**Comment by willweinstein** [comment]
@thatoddmailbox so its fixed? also, lets talk about those "50 websites you have" if you are hosting a school website (not school endorsed but school related) with all the followers you have, it might need a slight bit of priority over the others

**Comment by thatoddmailbox** [comment]
@willweinstein what is wrong with 50 websites? IIS is a smart server; the app pools go idle, the w3wp.exe process are terminated, and no extra resources are used.

Also, what did you not get about:

> I've moved it to its own server 

and

> I'm actually not sure if there are memory leaks.

but

> (leave this issue open though)

**Comment by willbarkoff** [comment]
I think this is fixed.
