### ISSUE TITLE
Tab to Switch Tabs

### ISSUE THREAD

**Issue by willweinstein** [PlanHubMe/PlanHub#128]
i wanna try and code it so dont take my fun away but i want to put in a system where hitting tab would cycle between the registered tags in the planner (hw, essay, project, etc.).

**Comment by thatoddmailbox** [comment]
@willweinstein Do you mean when you are writing an event?

**Comment by willweinstein** [comment]
@thatoddmailbox @nywillb @medensqui ALSO CAN WE HAVE A SKYPE GROUP THINGY

**Comment by willweinstein** [comment]
@thatoddmailbox umm like when you are writing a hw assignment

**Comment by willweinstein** [comment]
@thatoddmailbox also, can i be a member i can't edit code currently

**Comment by willweinstein** [comment]
@thatoddmailbox also where are you?

**Comment by thatoddmailbox** [comment]
@willweinstein GO ON SKYPE

**Comment by willweinstein** [comment]
@nywillb WILL CAN YOU GET A SKYPE OR TELL IT TO US. SKYPE IS FUN. SKYPE IS USEFUL.

**Comment by thatoddmailbox** [comment]
Done by @willweinstein!

**Comment by willweinstein** [comment]
@thatoddmailbox eym two pru fure yoo

**Comment by thatoddmailbox** [comment]
@willweinstein ?
