### ISSUE TITLE
If you press enter without a space after a calendar entry, it turns pink

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#136]

**Comment by thatoddmailbox** [comment]
@nywillb I think this is because the code is including the newline as part of the first word.

**Comment by thatoddmailbox** [comment]
Fixed!

**Comment by willweinstein** [comment]
@thatoddmailbox check before you close

**Comment by thatoddmailbox** [comment]
@willweinstein but I did

**Comment by willweinstein** [comment]
@thatoddmailbox but its worse than before

**Comment by willbarkoff** [comment]
@thatoddmailbox @willweinstein There is just no pull request for it. He fixed it.

**Comment by willweinstein** [comment]
@nywillb no he didn't, go on the planner and check

**Comment by willbarkoff** [comment]
> There is no pull request for it. He fixed it.

@willweinstein HE DID NOT MERGE IT!

**Comment by willweinstein** [comment]
@nywillb ARE YOU SURE? CUZ THE BUG IS DIFFERENT THAN DESCRIBED

**Comment by thatoddmailbox** [comment]
@willweinstein I think this has been fixed. If it hasn't, reopen, and explain exactly what you are talking about.
