### ISSUE TITLE
HTML/Jade

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#137]
@thatoddmailbox This is more of a question than an issue, but why did you use Jade instead of HTML?

**Comment by thatoddmailbox** [comment]
@nywillb 
- templating
- variables
- nice-looking-ness

**Comment by thatoddmailbox** [comment]
@nywillb Closing this issue&mdash;if what I said does not make sense/is not enough/you want to ask another question, re-open it!

**Comment by willbarkoff** [comment]
@thatoddmailbox okay, thanks!
