### ISSUE TITLE
A beta website?

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#143]
like beta.planhub.me?

**Comment by thatoddmailbox** [comment]
@medensqui eventually there will be staging.planhub.me

**Comment by medensqui** [comment]
@thatoddmailbox ok

**Comment by willbarkoff** [comment]
@thatoddmailbox We should make it happen kind of quickly so that we can see our changes without having to run node.js.

**Comment by willbarkoff** [comment]
@thatoddmailbox and I think that beta.planhub.me is a better name than staging.planhub.me.

**Comment by willbarkoff** [comment]
@thatoddmailbox We should also allow users to join the beta.

**Comment by willbarkoff** [comment]
@thatoddmailbox WE NEED TO GET THIS DONE. YOU ARE THE ONLY ONE WHO HAS CONTROL OVER THE DOMAIN SO YOU NEED TO DO THIS. Sorry for the caps lock.

**Comment by thatoddmailbox** [comment]
Done! Try [beta.planhub.me](http://beta.planhub.me/) or [staging.planhub.me](http://staging.planhub.me/)! (both go to the same place)

It should autoupdate from git, and has a different database. **Do _NOT_ use it as your actual planner, use the real site for that. The database may be cleared/destroyed/exploded at random, and the website is several times slower than the real one.**
