### ISSUE TITLE
Chrome Security Issue

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#145]
![Uh ohh... This can't be good](https://cloud.githubusercontent.com/assets/10969136/10804930/984309d4-7da0-11e5-954e-31eb469e43be.png)

**Comment by thatoddmailbox** [comment]
@nywillb Fixed; however, this may take a couple of minutes to begin working again.

**Comment by willbarkoff** [comment]
@thatoddmailbox What caused the issue?

**Comment by thatoddmailbox** [comment]
@nywillb CloudFlare, what we use for as a content provider, was being annoying, so I disabled it, to make connections straight to the server. Unfortunately, it broke the SSL certificate when I did that, making https requests get that message.
