### ISSUE TITLE
PLANHUB DOESN'T WORK

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#149]
:angry: @thatoddmailbox @nywillb @willweinstein

**Comment by thatoddmailbox** [comment]
@medensqui I'm assuming, because you closed this and it's working, PlanHub is working.

(I will move it to a less crashy server when it's released)

**Comment by medensqui** [comment]
@thatoddmailbox Yes it is working.

PUBLIC RELEASE IS TODAY WE BETTER GET TO WORK

**Comment by thatoddmailbox** [comment]
@medensqui WELL NOW IT'S TOMORROW

**Comment by medensqui** [comment]
@thatoddmailbox :100:

**Comment by medensqui** [comment]
@thatoddmailbox **I FULLY APPROVE**
