### ISSUE TITLE
How club people should contribute?

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#15]
Maybe pull requests?

**Comment by medensqui** [comment]
Paging @thatoddmailbox @nywillb

**Comment by medensqui** [comment]
ALSO HOW DO I CREATE NEW LABELS

**Comment by thatoddmailbox** [comment]
@medensqui GO TO THE ISSUES PAGE AND AT THE TOP CLICK LABELS AND THEN CLICK NEW LABEL

@medensqui We could add them to the organization on separate teams? we do actually need someone to take a bunch of screenshots. The "enable features" pages are somewhat empty.

**Comment by medensqui** [comment]
@thatoddmailbox 
THERES NO NEW LABEL BUTTON

But wouldn't they need to pull request so that they could have the OG code?

![screen shot 2015-10-26 at 8 15 57 am](https://cloud.githubusercontent.com/assets/12429395/10728637/d128af12-7bb9-11e5-99c6-0fd26656211a.png)

**Comment by thatoddmailbox** [comment]
@medensqui lolwhat? There is one for me. I will try and do some pokery on my end. 

what do you mean by OG code? This repo _is_ public....

They would be able to commit directly to the repo if they were in the org.

**Comment by medensqui** [comment]
@thatoddmailbox The original code.

Also, we don't want them to directly commit just in case they mess up stuff.
We should have them code on their own and then proofread and then implement

**Comment by thatoddmailbox** [comment]
@medensqui Ok it seems like GitHub didn't think you should be able to write to the repo. I fixed that. It should work now. 

Then yes, have them fork and pull. We can look at the pull and approve it. 

Also, GitHub lets you do _fancy_ things with pull requests. You can make tests that have to pass before the pull is accepted, for example.

**Comment by medensqui** [comment]
@thatoddmailbox Ok.

So like a test to make sure the code isn't broken?

**Comment by thatoddmailbox** [comment]
@medensqui If we get really fancy, we can write unit tests. They basically run a function or small segment of code and check the result is what it expects. Otherwise, it gives a warning.

**Comment by medensqui** [comment]
@thatoddmailbox Good idea!

**Comment by thatoddmailbox** [comment]
Closing this because it seems like we've figured out this part.
