### ISSUE TITLE
Planner Lab Section?

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#150]
??? @thatoddmailbox

**Comment by thatoddmailbox** [comment]
@medensqui Right now, you can create a row called "Lab" and put events with the Lab tag in them. Or do you mean something else?

**Comment by willweinstein** [comment]
@medensqui @thatoddmailbox maybe it could put labs in once the schedule feature works

**Comment by thatoddmailbox** [comment]
@willweinstein yes but then why is this public release

**Comment by medensqui** [comment]
@thatoddmailbox True

**Comment by willweinstein** [comment]
@thatoddmailbox i never said it was public release that was josh

**Comment by thatoddmailbox** [comment]
@medensqui As I understand it, this is the same as #9, so I'm closing it.
