### ISSUE TITLE
Blank Lines Bug (duplicate)

### ISSUE THREAD

**Issue by willweinstein** [PlanHubMe/PlanHub#160]
When you delete text from a box, it generates an enter in that box until you put other text in or studer deletes it (yes unless those happen, it is immortal)

**Comment by thatoddmailbox** [comment]
@willweinstein This has probably been partially fixed by #170. Fixing #173 should also close this.

**Comment by thatoddmailbox** [comment]
@willweinstein Actually, I think this is a duplicate of #173. Closing...
