### ISSUE TITLE
Emails

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#167]
I realized that maybe before we do #125 (emailing beta testers), we may want to actually have an email server in place.

Also, I'm not sure how to make individual emails work again. I might just attach this to the CoursesPlus Internal stuff.

paging @medensqui @nywillb @willweinstein

**Comment by medensqui** [comment]
@thatoddmailbox That works, also should we promote it to C+ users?

**Comment by thatoddmailbox** [comment]
@medensqui maybe not now, but as things stabilize maybe. Or maybe we should do it if/when CoursesPlus gets a PlanHub service.

**Comment by willweinstein** [comment]
@thatoddmailbox courses plus internal stuff? pls explain, i dont really know anything about courses plus

**Comment by thatoddmailbox** [comment]
@willweinstein it is an evil secret control panel for coursesplus people where they can sign in and do admin stuff and check their email.

**Comment by willweinstein** [comment]
@thatoddmailbox am I on it? pls dont be annoying because if you just put planhub stuff on the coursesplus internals, i wont be able to do anything

**Comment by thatoddmailbox** [comment]
@willweinstein Now you are not, but if I put the planhub stuff on it, you would be.

**Comment by willweinstein** [comment]
@thatoddmailbox ok

**Comment by willbarkoff** [comment]
@thatoddmailbox https://www.zoho.com/mail/

**Comment by thatoddmailbox** [comment]
@nywillb but 10 users, storage limits, and can't easily connect scripts and programs to it. The nice thing about hosting a mail server (like for CoursesPlus) is that you can make programs connect to it and autorespond to emails and fun things.

**Comment by willbarkoff** [comment]
@thatoddmailbox Found It!
PHP: http://www.afterlogic.com/webmail-client
ASP.NET: http://www.afterlogic.com/webmail-client-asp-net

**Comment by thatoddmailbox** [comment]
@nywillb ummm. The PHP version of AfterLogic webmail lite is what's already used for CoursesPlus, and would be used for PlanHub email too.

We don't have Pro because that costs monies.

**Comment by willbarkoff** [comment]
Yes

**Comment by thatoddmailbox** [comment]
@nywillb ?

**Comment by willbarkoff** [comment]
@thatoddmailbox http://www.afterlogic.com/wiki/Branding_(WebMail) for coursesPlus (it might be only pro)

**Comment by willbarkoff** [comment]
@thatoddmailbox is this finished, if so, how do we access our accounts?

**Comment by thatoddmailbox** [comment]
@nywillb plox look at slack for things

**Comment by amazansky** [comment]
Channel?

**Comment by thatoddmailbox** [comment]
This has been done; if you don't have an email, annoy me on Slack.
