### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by willweinstein** [PlanHubMe/PlanHub#169]
OUR LOGIN METHOD SEEMS KINDA SKETCHY, WE SHOULD GET NEW LAB TO GIVE US THE THINGY TO ACTUALLY LOG IN INSTEAD OF CHECKING TO SEE IF ONES LOGIN DETAILS WORK ON SCHEDULES

**Comment by thatoddmailbox** [comment]
@willweinstein It seems like you can also ask the computer science people. [See this page](https://sandbox.dalton.org/webapps/auth/index.php).

**Comment by thatoddmailbox** [comment]
@willweinstein or we could "borrow" the code that daltonplanner uses to connect to that service, but that would be even sketchier...

**Comment by willweinstein** [comment]
@thatoddmailbox LETS ASK NEW LAB

**Comment by willweinstein** [comment]
@thatoddmailbox OR MAYBE DR. WARREN, IT SAYS COMPSCI TEACHERS AND HE SEEMS NICER

**Comment by medensqui** [comment]
@willweinstein AND HE WILL ACTUALLY DO STUFF UNLIKE NEW LAB

**Comment by willbarkoff** [comment]
@PlanHubMe/leaders  Can one of you send the email?

**Comment by thatoddmailbox** [comment]
@nywillb ?

**Comment by willbarkoff** [comment]
I have no preference.

**Comment by thatoddmailbox** [comment]
@nywillb I was talking about

> @PlanHubMe/leaders Can one of you send the email?

because I didn't understand what you were referring to.

**Comment by willbarkoff** [comment]
@thatoddmailbox Oh, I meant can someone else send an email or talk to them? I am kinda really bad at emails.

**Comment by thatoddmailbox** [comment]
@nywillb why did you mark this as security? Using schedules is no less secure than Dalton's api thing

**Comment by willbarkoff** [comment]
@thatoddmailbox Because login kinda has to do with **PASSWORDS** and passwords **KINDA HAVE TO DO WITH SECURITY**!

**Comment by willweinstein** [comment]
@PlanHubMe/coders are we talking to someone about using an official api eventually????????????

**Comment by thatoddmailbox** [comment]
@willweinstein maybe we could bug new lab to set up a thingy for whipplehill SSO so we could use that (like Google Docs)

**Comment by todd-lm** [comment]
Wait, you guys take my login, put it on schedules and see if that works or not and just accept that?

**Comment by thatoddmailbox** [comment]
@Tpixelminer Yes, we right now use schedules to check usernames and passwords.

**Comment by willweinstein** [comment]
@thatoddmailbox I don't think any progress will be made with this as new lab probably wouldn't make a whole login system for us and the comp-sci department says there is no official api.

**Comment by willbarkoff** [comment]
@thatoddmailbox @willweinstein I will go to the new lab after school and ask them about an API. We might as well try.

**Comment by thatoddmailbox** [comment]
@nywillb @willweinstein said api was shutdown (try going to the link at the top of this page).

**Comment by thatoddmailbox** [comment]
> I don't think any progress will be made with this as new lab probably wouldn't make a whole login system for us and the comp-sci department says there is no official api.

seems to be the case. I __guess__ we could write something that did an LDAP bind, but not only would we have to keep that in the Dalton network (somehow), it would also not be any better than what we have now.
