### ISSUE TITLE
Overview should actually do something

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#17]
but I'm not sure what.

Maybe it could tie in to your planner and be like "oh, you have &lt;a lot/a medium amount of/not so much> homework for tomorrow".

**Comment by medensqui** [comment]
@thatoddmailbox Great idea! Yes pls

**Comment by em-p** [comment]
IT SHALL DISPLAY RANDOM GIFS FROM GIPHY

**Comment by willweinstein** [comment]
@em-p ...

**Comment by willweinstein** [comment]
@thatoddmailbox why dont we just make it say you have ___ HWs coming up, you have ____ Tests coming up, etc.

**Comment by willweinstein** [comment]
@thatoddmailbox ?

**Comment by willbarkoff** [comment]
@thatoddmailbox or @willweinstein or @RobotXLabs or @nywillb
Lets do this:

> Maybe it could tie in to your planner and be like "oh, you have <a lot/a medium amount of/not so much> homework for tomorrow".

-@thatoddmailbox
