### ISSUE TITLE
Blank Lines Bug

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#170]
This is related to #160

Every time you load a week, it adds another line to each box. This line is then stored in the database and saved. When you load the week again, it adds another line to each box. This repeats over and over until you have really long boxes or a full database.

Currently, the database has 870 blank text rows.

:frowning:

**Comment by medensqui** [comment]
@thatoddmailbox ITS SO ANNOYING. B/C I SCROLL AND IT SCROLLS MY BOXES. YARG IM RANTING SO HARD RN

**Comment by thatoddmailbox** [comment]
@mednesqui SORRY I HAVE PE RIGHT NOW.

SO FAR I AM DELETING THE LINES BETWEEN CLASSES!

**Comment by thatoddmailbox** [comment]
Confirmed fixed!

Now I have to fix #173...

**Comment by medensqui** [comment]
@thatoddmailbox YAY
