### ISSUE TITLE
Deletable event lines

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#173]
You should be able to delete new lines you add to events.

**Comment by willweinstein** [comment]
@thatoddmailbox i dont understand what you are saying... please explain. events? lines? deletion? I DONT UNDERSTAND

**Comment by thatoddmailbox** [comment]
@willweinstein 

### tl;dr: if it doesn't have a subId of 0, it's stuck forever/until I clear the db.

#### Steps to reproduce
1. go to planner
2. write two lines in any box
3. reload
4. look at box
5. delete second line
6. reload
7. notice how the box still has a line (it probably will have two blank line)
8. try to delete the blank lines
9. reload
10. see how lines are still there
11. be sad

**Comment by willweinstein** [comment]
@thatoddmailbox why u make me so sad

**Comment by thatoddmailbox** [comment]
@willweinstein what?

**Comment by willweinstein** [comment]
@thatoddmailbox 

>  11. be sad

**Comment by thatoddmailbox** [comment]
@willweinstein 
Oh, that.

:P

**Comment by thatoddmailbox** [comment]
This is partially fixed as of the latest commit.

**Comment by thatoddmailbox** [comment]
Yay I think it's fixed (haven't yet merged to master though)

**Comment by amazansky** [comment]
Um don't think so unless you didn't yet put it on stable...

**Comment by willbarkoff** [comment]
@robotXlabs:

> haven't yet merged to master though)

 _- @thatoddmailbox_

**Comment by willbarkoff** [comment]
Sorry, Closed by accident

**Comment by thatoddmailbox** [comment]
This is finished, so it _should_ be closed.

**Comment by willbarkoff** [comment]
:facepalm:

**Comment by willbarkoff** [comment]
^What happened to the emoji?^

**Comment by thatoddmailbox** [comment]
@nywillb we had a facepalm icon?

**Comment by willbarkoff** [comment]
I thought so

**Comment by willbarkoff** [comment]
Look at #167
