### ISSUE TITLE
Tour

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#178]
We should have a tour so new users know how things work.

**Comment by thatoddmailbox** [comment]
@nywillb Maybe we could use [this library](http://fgribreau.github.io/bootstrap-tour/docs/bootstrap-tour.js.html) or something better for it.

**Comment by medensqui** [comment]
@thatoddmailbox MAKE IT LIKE THE APPLE TOUR I SHOWED YOU. Wait that's way too unrealistic nvm. Umm I don't have bootstrap so I can't see it. HOW DO I INSTALL BOOTSTRAP

**Comment by thatoddmailbox** [comment]
@medensqui 

> HOW DO I INSTALL BOOTSTRAP

? That is something the website owner has to install.

I think the demo on that site is broken..

**Comment by thatoddmailbox** [comment]
@medensqui I FOUND A BETTER TOURING LIBRARY. [Click](http://easelinc.github.io/tourist/).

**Comment by medensqui** [comment]
@thatoddmailbox Ah yes. Also the library that you now have found is superior

**Comment by thatoddmailbox** [comment]
@medensqui Wait no that one needs Backbone.

:(

**Comment by thatoddmailbox** [comment]
@medensqui I FOUND A BETTER ONE THAT REALLY WORKS! [Click me for real](http://usablica.github.io/intro.js/).

**Comment by medensqui** [comment]
@thatoddmailbox Yes agreed. Was a bit suspicious of that link...Also WORK ON MY DAY YARG KFJDSKLA:DKJFLDKGF:RWJLEGFRE:JLRKFGBEOWPQIEJLKGRFEOQIJdgz

**Comment by thatoddmailbox** [comment]
@medensqui 

> Was a bit suspicious of that link..

[super legit link](http://bringvictory.com)

> WORK ON MY DAY

YARG KFdaklfjasdlfasdcasdcasdkcASKDSACJASCKL

**Comment by medensqui** [comment]
@thatoddmailbox Chrome hover on link gets url ftw

WORK ON MY DAY

**Comment by thatoddmailbox** [comment]
@medensqui >Chrome hover on link

[GWEHEHEHE](http://a/%%30%30)

> WORK ON MY DAY

YARG asdfasdfasdagswefwwrtw4gyireiuh

**Comment by medensqui** [comment]
@thatoddmailbox ...
YARG WORK ON MY DAY

**Comment by thatoddmailbox** [comment]
@medensqui I ALREADY TOLD YOU

@c20et wants to submit it to the hackathon, which means we cannot work on it yet. I don't think we should, though.

**Comment by medensqui** [comment]
@thatoddmailbox WE SHOULD NOT BC WE WILL GET MINUS POINTS

WHAT ABOUT FIRST CLASS PLUS

**Comment by thatoddmailbox** [comment]
@medensqui 

> MINUS POINTS
> ?

FirstClass Plus could work, but we've already started that too.

:/

**Comment by medensqui** [comment]
@thatoddmailbox YARG. OK...

LETS DO A GAME EVERYONE LIKES GAMES

**Comment by thatoddmailbox** [comment]
@medensqui can you go on skype so we can talk about it there? Idk if a game is allowed...

**Comment by medensqui** [comment]
@thatoddmailbox OR ENCORPORATE ALL THE APIS OF THE SPONSORS
Ebay, Square, BuzzFeed, etc.

**Comment by amazansky** [comment]
So guys this is done (click the start button on staging overview), but how do we incorporate it so that the user sees it only the first time he/she enters planhub?

**Comment by willweinstein** [comment]
@RobotXLabs we could write a knex and once it is clicked it sets a row in a db to 1 and it checks if that row != 1 in order to exist maybe?

**Comment by amazansky** [comment]
That might work. Idk really how to write any Knex.
Paging @PlanHubMe/coders (who know knex)
How do I do it?
Actually someone else do it
I will make the button a bit more shinyful for now

**Comment by thatoddmailbox** [comment]
@willweinstein @RobotXLabs we could just trigger it if it detects you do not have anything enabled.

**Comment by willbarkoff** [comment]
@thatoddmailbox @willweinstein @RobotXLabs What we could do is on overview put an "alerts" section, then for users that have not dismissed the alert, an alert will appear asking them to press the button. See [this](http://getbootstrap.com/components/#alerts-dismissible) and issue #241

**Comment by thatoddmailbox** [comment]
but if it's your first time, you might ignore/skip the tour, and that doesn't change the fact that you'd have to knex some more stuff.

**Comment by willbarkoff** [comment]
@thatoddmailbox what do you mean?

**Comment by thatoddmailbox** [comment]
@nywillb the easy way, which doesn't need to modify the database schema, is to trigger the tour when no features are enabled.

**Comment by thatoddmailbox** [comment]
Yay this is done.
