### ISSUE TITLE
It is ugly if you delete all of your subjects.

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#179]
![it looks kinda really ugly](https://cloud.githubusercontent.com/assets/10969136/10900094/90d5f320-81a9-11e5-861d-48c4733a5561.png)

**Comment by thatoddmailbox** [comment]
@nywillb :/. It should probably show a message saying "welcome to Planner, click the add subject button to add a subject" or something like that.

**Comment by willweinstein** [comment]
@nywillb well then maybe dont delete all subjects

**Comment by willbarkoff** [comment]
@willweinstein Ha
@thatoddmailbox Good idea!
