### ISSUE TITLE
Get Started Page should not show if you are logged in

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#18]
It should go straight to overview

**Comment by thatoddmailbox** [comment]
@medensqui I think we should keep it this way. There is a "Go to Overview" button in the top right, and this way you don't have to sign out if you want to see the front page or about page when we make those.

**Comment by medensqui** [comment]
@thatoddmailbox True!

**Comment by medensqui** [comment]
@thatoddmailbox Get Started should link to overview when signed in though

**Comment by thatoddmailbox** [comment]
@medensqui but it does though. (I haven't updated planhub.me yet, but I will)

**Comment by medensqui** [comment]
@thatoddmailbox Ok. Do the updates go immediately on the azure server?

**Comment by thatoddmailbox** [comment]
@medensqui No, I have to update it manually. I think what I will do is make it so it only updates to specifically marked releases. Like if we tag a release as "stable" then it automagically updates it, but otherwise ignores it.

But for now, no, I have to poke it.

**Comment by thatoddmailbox** [comment]
YAY THIS IS FIXED

**Comment by medensqui** [comment]
@thatoddmailbox OK THEN POKE IT
Smart idea for stable

YAY

**Comment by thatoddmailbox** [comment]
@medensqui I DID POKE IT
