### ISSUE TITLE
yay I made a status page

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#183]
[status page](http://status.planhub.me)

**Comment by medensqui** [comment]
@thatoddmailbox yay what about a beta page.

Closing this issue

**Comment by thatoddmailbox** [comment]
@medensqui the beta page works [click](http://beta.planhub.me) but doesn't auto-update **yet**. :(

**Comment by medensqui** [comment]
@thatoddmailbox yay :cry:

**Comment by thatoddmailbox** [comment]
@medensqui yay but sad?

**Comment by medensqui** [comment]
@thatoddmailbox LIKE IT DIDNT AUTOMAGICAL UPDATE PLUS IT DOESNT SYNC
