### ISSUE TITLE
My Day questions

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#190]
We need a list of questions to ask the user when they start My Day (the preferences form)

@medensqui could you write a list here/commit the changes/somehow figure out a list of questions?

**Comment by medensqui** [comment]
@thatoddmailbox Ok I'll make a list...

**Comment by willbarkoff** [comment]
Here I some things I think we need.
- [x] Homework
- [x] Afterschool Activities
- [ ] Travel Time
- [x] Wakeup Time

**Comment by medensqui** [comment]
@nywillb ok

**Comment by medensqui** [comment]
@nywillb We have address which can calculate your commute

**Comment by medensqui** [comment]
@nywillb Or will be able to eventually

**Comment by c20ms1** [comment]
If you include commuting information, will you be using something like the Waze API, and embed something like Waze, or build it from the ground up?

**Comment by thatoddmailbox** [comment]
@c20ms1 We were thinking Google Maps (for traffic), but Waze actually is a better idea, as it is more up-to-date!

**Comment by medensqui** [comment]
@thatoddmailbox Only problem w/ waze, only has car traffic...No public transportation and walking.

**Comment by thatoddmailbox** [comment]
@medensqui walking traffic? Though there is the point with public transport... It would be similar, though, as buses use the streets. You could also see if the MTA has an API for the [Bus Time](http://bt.mta.info) and Subway Time (don't know link, but you can search it) apps.

**Comment by willbarkoff** [comment]
@medensqui They have an API: http://bt.mta.info/wiki/Developers/Index;jsessionid=9C939A4F880CEC172C29ED53615FF085

**Comment by thatoddmailbox** [comment]
The actual form and saving of the info is done. If you want to add more/do something else/change something, make another issue, like #350.
