### ISSUE TITLE
Title Switching Prefs

### ISSUE THREAD

**Issue by willweinstein** [PlanHubMe/PlanHub#195]
Users should be able to set a preference for the order in which tab toggles between tags. This would also be part of #161 which can i do it alone? I WANNA DO MORE AND IT SEEMS NO ONE IS FOCUSING ON IT ANYWAY

**Comment by medensqui** [comment]
@willweinstein GOOD IDEA
OK FINE YOU CAN DO MORE
THE ONLY PROBLEM IS THAT WE ARE FOCUSING ON FEATURES LIKE MY DAY THAT SET US APART YARG
ALSO GO AHEAD DO IT ALONE JUST DON'T BREAK ANYTHING

**Comment by willweinstein** [comment]
@medensqui i havn'e broken anything but can't write knex really so its not going so well

**Comment by willweinstein** [comment]
finished!
