### ISSUE TITLE
Error Report Form

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#201]
When someone uses the error report form, the error report will appear here.

**Comment by willbarkoff** [comment]
@PlanHubMe/coders @PlanHubMe/designers @PlanHubMe/idea-thinkers I need someone to comment on this issue to get this set up.

**Comment by thatoddmailbox** [comment]
@nywillb are you talking about the feedback? That will go on the admin tab (there is already a semi-working version of it in staging). It _could_ post here, but they contain personal information (name, username, _maybe_ contents of page) that shouldn't be posted on this public issue.

**Comment by willbarkoff** [comment]
@thatoddmailbox, no a form for broken link type things and stuff like that.

**Comment by thatoddmailbox** [comment]
@nywillb Oh. Do we have one? There aren't many pages/links that could break on PlanHub... The only way to get to a broken pages is to `setPage()` to a non-existent page or mess with the hash in the URL (what comes after the `#`)

**Comment by willbarkoff** [comment]
@thatoddmailbox You are right, but we need one for APIDocs and PlanHubHelp.

**Comment by thatoddmailbox** [comment]
@nywillb Oh. Did you put this in the wrong repository?

**Comment by willbarkoff** [comment]
@thatoddmailbox yes.
