### ISSUE TITLE
Admins don't have admin access on staging

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#202]
@thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox @thatoddmailbox

**Comment by thatoddmailbox** [comment]
@medensqui SORRY I FIXED IT YAY
