### ISSUE TITLE
Loading timeout

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#204]
The "Loading" screen can stay stuck forever even if there was an error. It would be good to have it timeout after 10-15 seconds with an error message.

**Comment by willweinstein** [comment]
@thatoddmailbox sensible people will reload the page, idiots will be trapped and die staring at the screen. _SURVIVAL OF THE FITTEST_

**Comment by thatoddmailbox** [comment]
@willweinstein Somehow, survival of the fit does _not_ seem like a good idea. Also, before about 30 seconds, people will think "oh, PlanHub is so slow, :(" when it's really that something happened and caused it to stop.

**Comment by medensqui** [comment]
yay

**Comment by thatoddmailbox** [comment]
@medensqui You can test this by going to staging, running `window.page.showLoading()`, and waiting 10 seconds.

ALSO LOOK AT THE SHINY SWAP INTERFACE!

**Comment by medensqui** [comment]
@thatoddmailbox YAY MERGE PLS
