### ISSUE TITLE
☹, ☺︎, and Idea Buttons

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#211]
Self Explanatory

**Comment by thatoddmailbox** [comment]
@nywillb They _work_ (as in they are taken and saved to the db), but the feedback page is still under development and is kind of broken and doesn't show them.

**Comment by willbarkoff** [comment]
:P

**Comment by willweinstein** [comment]
@thatoddmailbox could we make a thing to click on feedback and have the screenshot come up as a modal?

**Comment by thatoddmailbox** [comment]
@willweinstein the problem isn't taking the snapshot, the problem is the admin interface doesn't show it...

**Comment by willweinstein** [comment]
@thatoddmailbox like it doesn't or you haven't tried

**Comment by willbarkoff** [comment]
@thatoddmailbox lets try to get this done sooner rather than later,

**Comment by willbarkoff** [comment]
@thatoddmailbox Would it also be possible for us to have a GitHub Issue Checkbox and Issue Number to keep track of issues with github issues?

**Comment by amazansky** [comment]
Webhooks?
Maybe use the `issues` hook and link with `POST` to the issues page? (Just an idea...)

**Comment by willbarkoff** [comment]
We should be able to view c numbers so that way we can send emails.

**Comment by thatoddmailbox** [comment]
@nywillb I am not the only person that can do it. The admin feedback API already returns the username, it's just that the UI ignores it.

**Comment by willbarkoff** [comment]
Ok, I will add it now.
