### ISSUE TITLE
@nywillb being confuz

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#212]
@thatoddmailbox @willweinstein @medensqui
PEOPLE DO NOT LIKE ADS.

**Comment by medensqui** [comment]
@nywillb WE MEANT ADVERTISING OUR PRODUCT NOT ADS ON OUR WEBSITE!!!!!!

**Comment by willbarkoff** [comment]
@medensqui Ohhhhhhhhhh

**Comment by thatoddmailbox** [comment]
@nywillb What @medensqui said. The milestone is for when we can actually start telling people about it (announcement on CoursesPlus maybe?) and when we know that it probably won't crash and burn. Also at this point the code/db schema should be mostly stable and updates to the main site will probably be bigger, tested for longer, and less often.
