### ISSUE TITLE
Rewrite tag highlight system

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#215]
It would be nice if the tag system could be rewritten. The current system is very buggy, and fails if you try to move the textbox, make a long tag, or do pretty much anything...

**Comment by thatoddmailbox** [comment]
I've forked a plugin into [a repo](https://github.com/PlanHubMe/jquery-highlighttextarea). We have to tweak it somewhat, but it should be possible to make it work.

**Comment by medensqui** [comment]
@thatoddmailbox @nywillb When are you guys free after school? So we can plan DaltonTab b4 Wed so we can code. Also has Eeshan signed up/understand what we are doing?

**Comment by willbarkoff** [comment]
@thatoddmailbox @medensqui I am free today.
