### ISSUE TITLE
A way of overriding a user's planner.

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#218]
Here is how it can go:
1. Go to admin panel
2. Click user data override
3. Give unique link, (expires in 3 hrs) for user to sign in.
4. User signs in, goes to page verifying giving temporary (24 hr) account access to administrator who is helping you.
5. Administrator has various options, but **cannot edit events directly**.
6. Administrator selects "Finished" button.
7. Session is closed, and cannot be reopened without going back to step 1

Admin options:
- Erase all data
- Change user's name
- Export data (JSON)
  - Sends email to user with data
- Import data (JSON)
  - Sends email to user with unique line (expires in 3hrs) for user to paste data into.

This is a lot of programming work, but it can be useful.

**Comment by willbarkoff** [comment]
@thatoddmailbox You know about Mandrill that could trigger the email, and I know that ruby has a way of sending emails to users.

**Comment by thatoddmailbox** [comment]
@nywillb it's doable, but will take a lot of effort. What would make this better than the snapshot function (when that gets working) or giving the user import/export functions? Also mandrill probably has a node.js library, and I do not think it is a good idea to have a tiny part of the code be in ruby just for sending emails...

**Comment by willweinstein** [comment]
@nywillb there is already a page to change your name, no admin access required... its just _secret_

**Comment by willbarkoff** [comment]
@willweinstein I know, `setPage("prefs")`, but it changes the name for **feedback** also.

**Comment by thatoddmailbox** [comment]
@nywillb do you not want to have the name change for the feedback page?

**Comment by amazansky** [comment]
sorry it was accident

**Comment by amazansky** [comment]
Oh shoot I kept clicking the wrong one!
ARGH
I wont touch that button from now on
or I'll try anyway

**Comment by thatoddmailbox** [comment]
@nywillb question: what does this do? it seems like the real options, after doing the confirm thing, are

> Erase all data
> Change user's name
> Export data (JSON)
> Import data (JSON)

I'm not sure why you'd want to erase all of a user's data, the user can already change their name (not officially, but eventually it might be official, if we even want that option), and export and importing data, while useful, shouldn't be limited to bugging an administrator and should just be an option on a user settings page somewhere.

**Comment by amazansky** [comment]
No changing names now...
So just

> Erase all data
> Export data (JSON)
> Import data (JSON)

This is useful for what?

**Comment by thatoddmailbox** [comment]
@RobotXLabs see my comment above, but basically--erasing all data isn't so helpful, and export/import should be something a user can do by themselves.

**Comment by thatoddmailbox** [comment]
paging @nywillb

**Comment by thatoddmailbox** [comment]
@nywillb helloooooooo?

**Comment by willbarkoff** [comment]
@thatoddmailbox There needs to be a way of clearing data, and why would we need import and export?

**Comment by thatoddmailbox** [comment]
@nywillb you were the one who suggested import/export, and deleting all data shouldn't need an administrator...

**Comment by willbarkoff** [comment]
@thatoddmailbox Good point, and I don't know what I was thinking about.

**Comment by amazansky** [comment]
Close?

**Comment by thatoddmailbox** [comment]
@RobotXLabs Close!
