### ISSUE TITLE
HW View incorrect organazation

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#223]
HW View gets a little confused about months.

![I know how to adjust hover text in markdown! I am awesome!](https://cloud.githubusercontent.com/assets/10969136/11574291/c2468d88-99d8-11e5-9a35-96a5875a60a2.png)

**Comment by willweinstein** [comment]
@nywillb hwview is some spooky code written by almighty alex. idk whats going on there

**Comment by thatoddmailbox** [comment]
@nywillb Obviously tomorrow is 1/4! They both have 4, how different can that be?

This is probably from the _spooky_ replacement of the manual day-by-day search with a single database query. It shouldn't be too hard to fix...
