### ISSUE TITLE
Minor Issue(s)

### ISSUE THREAD

**Issue by c20ms1** [PlanHubMe/PlanHub#226]
# HW View Minor Issues
### Before Enabling HW

Before enabling the HW View, it says:

> ho,,,mework 

It's not a big issue, but I think it will probably be easy to correct.
### Disabling HW View

If the User enabled HW view but then suddenly reconsiders (for some reason) I think there should be an option to disable it.

_Thanks for Listening._

**Comment by medensqui** [comment]
@c20ms1 THANKS FOR YOUR FEEDBACK ABID! WE ARE DEFINITELY NOT WATCHING NOOT CENA VIDEOS WHILE CONSIDERING YOUR FEEDBACK. But seriously we are talking about it rn.

**Comment by willweinstein** [comment]
@PlanHubMe/coders im too lazy to unenable HW View or find wherever it is in the jade... is this fixed?

**Comment by amazansky** [comment]
I am a coder :) Umm let me check the Jade
If I understand you correctly, it says ho,,,mework before you enable it?

or the second part?

**Comment by amazansky** [comment]
K the first part has already been fixed.
Second: If a user decides to reconsider, they just won't use a certain feature :)

**Comment by willbarkoff** [comment]
@c20ms1 I believe this issue is closed. Is this correct?

**Comment by thatoddmailbox** [comment]
@nywillb No, you still cannot disable Homework View.

**Comment by thatoddmailbox** [comment]
@nywillb renaming Enable to Start does not fix this issue.

**Comment by willweinstein** [comment]
@thatoddmailbox there's no reason to disable hw view... the tab would still be existent... THIS IS NOT IMPORTANT WHATSOEVER
