### ISSUE TITLE
Security Issue?

### ISSUE THREAD

**Issue by c20ms1** [PlanHubMe/PlanHub#233]
# Security Issues
## Prelude

First, I'll ask if you guys are already connected with CloudFlare, and such DNS level DoS,and DDos 
protection services. If you are, disregard everything else I write, otherwise, the writing will be relevant.  
## Vulnerability?

Since I'm too thickheaded and bad at programming to understand the website's `.js` and `.jade` code, I was thinking about using brute force to crack usernames and passwords, and I realized something. If your website uses Courses, or Schedules to confirm the usernames and passwords, then whats stopping a hacker from using your website as a frontend to those Courses and Schedules services for bruteforcing? Second, what if they use this tactic in order to **_disable Planhub itself**_? Since Cloudflare from Courses and Schedule would block Planhub for the suspiciously frequent requests, then wouldn't that disable the service of logging in?
## Solutions

Either:
1. Make your own database of usernames and passwords
2. Set up Cloudflare (_Recommended_)
3. Or Trust in the Good of People Everywhere (_Not Recommended_)

_Thanks for Listening -Abid_

**Comment by thatoddmailbox** [comment]
@c20ms1 First off, let me thank you for actually being concerned about security. That is a _good thing_.

We do use CloudFlare for DDoS protection. (and also a free SSL certificate!) However, that does not completely stop smaller bruteforce attacks. While it is true that a malicious person could use PlanHub as a proxy for attacking Schedules (which is what we use to verify usernames and passwords), I don't think Schedules actually does any bruteforce protection. Obviously, that does not mean we shouldn't have our own bruteforce protection, but it does lower the urgency of adding it.

In addition, we also have plans for people from outside of Dalton to sign up with a PlanHub account. However, when that happens, we will still keep the "sign in with Dalton account" option. We would also takes steps to ensure that passwords are cryptographically secure (probably using `bcrypt`), and would not store passwords for Dalton students (instead relying on Schedules for those accounts).

If New Lab does decide it is worth it to add bruteforce protection to Schedules, we could always ask them to whitelist the PlanHub server IP address (remove the protection for requests coming from PlanHub servers) or use an official API for sign in (I know they used to have one, but it was removed for some reason that I don't know)

Again, it is a good question, and we probably missed something while programming PlanHub/setting up the server/something else, so please follow up with an additional ones!

**Comment by c20ms1** [comment]
@thatoddmailbox  _Thanks for the quicky reply!_
