### ISSUE TITLE
Ugly Datepicker

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#235]
Can we use [this](https://eonasdan.github.io/bootstrap-datetimepicker/) datepicker instead. It is more **_shiny_**!

**Comment by RobotXLabs** [comment]
Shiny? It's at least shiny. Why not **_AWESOMETASTICAL_**!

**Comment by willbarkoff** [comment]
@RobotXLabs Shiny is something you dont understand. It is an inside joke.

**Comment by willweinstein** [comment]
@RobotXLabs shiny is the most important part of a website

**Comment by willbarkoff** [comment]
@RobotXLabs Shiny is better than **_AWESOMETASTICAL**_!

**Comment by amazansky** [comment]
Oh. Okay, then shiny.

**Comment by willweinstein** [comment]
@nywillb this is not ugly........................

**Comment by willbarkoff** [comment]
I think @willweinstein closed by accident (I _definitely_ didn't hex him)

**Comment by thatoddmailbox** [comment]
@nywillb what makes you think that?
