### ISSUE TITLE
Navbar Messages

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#241]
There should be a program that pulls from ~/messages.txt and what it does is it displays a navbar message similar to Courses**Plus** with data in messages.txt.

**Comment by thatoddmailbox** [comment]
@nywillb this should use a slightly better system so we can do things like analytics and having the message go away when you click on it (like in CoursesPlus with the client ID system)

**Comment by willbarkoff** [comment]
But we should all be able to post messages.

**Comment by amazansky** [comment]
Could it be through admin or Internal?

**Comment by willbarkoff** [comment]
@thatoddmailbox would it be possible to make posting messages on Courses**Plus** work via internal?

**Comment by amazansky** [comment]
And also maybe we could use an incoming webhook thing to pull from internal and put on?
or something...

**Comment by willweinstein** [comment]
@PlanHubMe/coders maybe we could have an admin post announcements page and it could appear for a set amount of time on the overview page?
