### ISSUE TITLE
HW View Problems

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#242]
I shouldn't say "Study in <subject name> due <due date>", It should say "Study <subject name> by 
<due date>.

**Comment by willbarkoff** [comment]
@thatoddmailbox Actually it is not fixed. It now says Study in <subject name> on <due date>.

> It should say "Study <subject name> by <due date>.

**Comment by amazansky** [comment]
Fixed as soon as @thatoddmailbox pokes.

**Comment by amazansky** [comment]
Fixed
