### ISSUE TITLE
HW View doesn't work

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#25]
It does literally nothing

**Comment by medensqui** [comment]
@thatoddmailbox

**Comment by thatoddmailbox** [comment]
@medensqui You have to have HW in your planner first.

**Comment by medensqui** [comment]
@thatoddmailbox Ah.

Quick note though, planner doesn't have enough tags. You should be able to create tags.

**Comment by thatoddmailbox** [comment]
@medensqui That is true. Do you have any ideas for more tags to add?

**Comment by medensqui** [comment]
@thatoddmailbox
I'll make a list and implement unused ones
- Paper
- Project
- Lab Report
  I'll tell you when I find more.

People should be able to make custom tags for their needs also

**Comment by medensqui** [comment]
@thatoddmailbox Reading, for English/History

**Comment by thatoddmailbox** [comment]
@medensqui Paper, Project, Report, and Reading are already tags...

**Comment by medensqui** [comment]
@thatoddmailbox ICE? (in class essay) Test? Quiz? Just making sure that all are made

**Comment by thatoddmailbox** [comment]
@medensqui Test and Quiz and IC**A** is there. So is "Essay". [Here](https://github.com/PlanHubMe/PlanHub/blob/9ccadec65562fc5fed0ee5b9cfeb797183ff0911/public/js/utils.js#L83) is the list of current tags.

**Comment by thatoddmailbox** [comment]
@medensqui Is HW view working now? Can I close the issue?

**Comment by medensqui** [comment]
@thatoddmailbox Ok

**Comment by thatoddmailbox** [comment]
@medensqui I'm going to close this now.
