### ISSUE TITLE
No Homework Nights

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#251]
A user has requested the feature to have an option for No Homework Nights. I don't know how the user will be promted? Ideas anyone?

**Comment by thatoddmailbox** [comment]
@nywillb probably when the user types in "No HW" or "None" or something similar, it will automatically fade the box grey (like when you mark as done) and hide it from HW view.

**Comment by willbarkoff** [comment]
Ok, great! Let's implement it, then I will notify the user that their
feature has been implemented.

**Comment by amazansky** [comment]
Has this been done yet? If not, I could give it a shot

**Comment by amazansky** [comment]
Finished with pull #253
