### ISSUE TITLE
No HW then HW bug

### ISSUE THREAD

**Issue by willweinstein** [PlanHubMe/PlanHub#255]
"none" works but if you try to add lines, the coloring system bugs out. (this may seem contradictory... who would want to add lines when there is no hw, but its still a bug and also maybe they want to write like a note to themselves or something idk)

**Comment by amazansky** [comment]
LOL, Bad things happen when you put in `padding:1000px;.

![Screen Shot](https://cloud.githubusercontent.com/assets/11902347/11766638/72a6ff18-a15f-11e5-8c32-abc5f87e7242.png)

I will look at it with @thatoddmailbox and see what might have gone wrong

**Comment by amazansky** [comment]
low priority b/c who types none and then hw

**Comment by thatoddmailbox** [comment]
@RobotXLabs @willweinstein it might just be easier to detect when you have typed in "none" or "nohw" and then just block any more typing, apart from backspace.

**Comment by willweinstein** [comment]
@thatoddmailbox thats a lotta work tho

**Comment by willbarkoff** [comment]
Is this really nessicary?

**Comment by thatoddmailbox** [comment]
@willweinstein probably easier than fixing the funky tag system

@nywillb Yes.
