### ISSUE TITLE
Planbot (whatever that means?)

### ISSUE THREAD

**Issue by em-p** [PlanHubMe/PlanHub#256]
yay planbot code w/ Emlyn aka code for Emlyn cause Alex wont tell Emlyn how Planhub works

**Comment by thatoddmailbox** [comment]
@em-p what?

**Comment by willbarkoff** [comment]
@em-p This is not an issue... closing.

**Comment by em-p** [comment]
rude

**Comment by willbarkoff** [comment]
:stuck_out_tongue:

**Comment by thatoddmailbox** [comment]
@nywillb I think you mean :stuck_out_tongue:
