### ISSUE TITLE
Print Formatting

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#259]
When the user hits Ctrl+P or ⌘+P it should re-format the page to make a print compatible layout.

**Comment by willweinstein** [comment]
@nywillb and when they type Ctrl+HEX it should hex the nsa...... (i am saying WHY IS THIS NECESSARY)

**Comment by willbarkoff** [comment]
@willweinstein This is why it is nessicary:
[PlanHub.pdf](https://github.com/PlanHubMe/PlanHub/files/62452/PlanHub.pdf)
[PlanHub2.pdf](https://github.com/PlanHubMe/PlanHub/files/62453/PlanHub2.pdf)

**Comment by thatoddmailbox** [comment]
This probably will use a separate `print` stylesheet that does magical CSS stuff, rather than trying to detect when you press the print button.

**Comment by amazansky** [comment]
Should be done with #275.
Closing it, but when are we going to pull and poke?
Paging @thatoddmailbox
