### ISSUE TITLE
Jump to Today Button

### ISSUE THREAD

**Issue by willweinstein** [PlanHubMe/PlanHub#262]
self explanatory... while I'm here, wasn't spellcheck supposed to be turned off in the planner?

**Comment by thatoddmailbox** [comment]
The jump to date already has a yellow tint on the current day, but there should be a "Today" button

**Comment by willweinstein** [comment]
@thatoddmailbox i mean if you go like a month in the future its so tedious to get all the way back and find that yellow box

**Comment by willbarkoff** [comment]
@willweinstein if you click the planner tab while you are far in the future, then it jumps back to the current day.

**Comment by willbarkoff** [comment]
@thatoddmailbox we can always just make jump to date reload the page.

**Comment by amazansky** [comment]
let me try that

**Comment by amazansky** [comment]
didnt work but have to go now. note to self (or whoever does this) use `location.reload`

**Comment by amazansky** [comment]
I think that covers it. Poke server. Umm also, this may be a future improvement, but maybe we shouldn't have it reload the page but instead do something kind of similar to the calendar when we click a date.
Oh well, works for now.
