### ISSUE TITLE
RACES ARE NO FUN

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#270]
`prefs.js` (and maybe other files?) have Time-of-check-to-time-of-use (TOCTTOU) bugs. If you call `prefs/set` quickly enough, multiple rows will be created in the database. This is not a security issue (at least not from what I've found...) but should still be fixed. This probably should be fixed (table locking?)

**Comment by willweinstein** [comment]
@thatoddmailbox I dont know what table locking is but races are fun

**Comment by amazansky** [comment]
Would this be considered a TOCTTOU bug?
![tocttou bug](https://cloud.githubusercontent.com/assets/11902347/12128632/7f4cca5c-b3cc-11e5-98bc-05a99bcd4c59.png)
To simulate: Click on HW view many times fast before it loads in sidebar
Everything is repeated the amount of times you click and it gives you the no homework alert

**Comment by thatoddmailbox** [comment]
@RobotXLabs No, that's the tab loader thingy not canceling the HW View loader.

**Comment by willbarkoff** [comment]
@thatoddmailbox GO ON SLACK

**Comment by thatoddmailbox** [comment]
![screen shot 2016-01-06 at 9 43 49 pm](https://cloud.githubusercontent.com/assets/1904587/12160927/9e083024-b4be-11e5-9667-c60919f3d7fc.png)

**Comment by thatoddmailbox** [comment]
![screen shot 2016-02-20 at 11 26 37 am](https://cloud.githubusercontent.com/assets/1904587/13197757/d9d8da62-d7c4-11e5-8d5d-c3fe4f7d2e57.png)

:disappointed:

**Comment by thatoddmailbox** [comment]
This seems to be fixed (along with another **really bad** bug with prefs!)
