### ISSUE TITLE
Address npm dependency issues found in master branch [Opened by bitHound]

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#272]
<p>bitHound discovered:</p> <ul> <li>1 package with at least one security vulnerability.</li> <li>3 unused packages.</li> <li>4 outdated packages.</li> </ul> <p>For details go to <a href="https://www.bithound.io/github/PlanHubMe/PlanHub/master/dependencies/npm">bitHound</a>.</p>

**Comment by thatoddmailbox** [comment]
@nywillb jade is already at the latest version. (even though bitHound claims it's insecure). Though the other packages should be updated, we should do it carefully. Some of them have a major version increase.

**Comment by thatoddmailbox** [comment]
See https://github.com/pugjs/jade/issues/2072. It does not look like we can fix this security bug (if there even is one) until jade 2.0 comes out and we upgrade...
