### ISSUE TITLE
Address issues found in public/js/planner.js [Opened by bitHound]

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#274]
bitHound discovered 12 LintIssues, 1 DuplicateFunction, and 2 ComplexFunctions in [public/js/planner.js](https://github.com/PlanHubMe/PlanHub/blob/5d65466aa52685aec6efa32cb4d3de2f7cf75409/public/js/planner.js). For details go to [bitHound](https://www.bithound.io/github/PlanHubMe/PlanHub/blob/5d65466aa52685aec6efa32cb4d3de2f7cf75409/public/js/planner.js).

**Comment by willweinstein** [comment]
@nywillb bitHound also had problems with our comments... Lesson: bitHound isn't so reliable
