### ISSUE TITLE
Profanity Filter

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#29]
We should not allow users to type bad words into the planner.

**Comment by medensqui** [comment]
@nywillb Lol no
https://www.law.cornell.edu/constitution/first_amendment

**Comment by willbarkoff** [comment]
@medensqui What if we replaced bad words with appropriate words that have equal meanings. That would not violate the first amendment (even though not allowing users to type bad words does not either). https://www.constituteproject.org/constitution/United_States_of_America_1992?lang=en#131

**Comment by medensqui** [comment]
@nywillb or just star it out

**Comment by willbarkoff** [comment]
I think that my idea is better. People will think it is funny.

**Comment by willbarkoff** [comment]
@medensqui Also, can you give me write access to this repository or does @thatoddmailbox have to do it?

**Comment by medensqui** [comment]
@nywillb How would I do that?

**Comment by thatoddmailbox** [comment]
@nywillb but why? If you type profanity in, no one sees it but you.

**Comment by willweinstein** [comment]
@nywillb who cares about profanity. if they typed it in thats their planner. unless you are planning some instant chat room for everyone on the planner (idea) then there is no purpose of this

**Comment by thatoddmailbox** [comment]
@willweinstein 

> instant chat room for everyone on the planner (idea)

No.
