### ISSUE TITLE
Unsafe Scripts?

### ISSUE THREAD

**Issue by amazansky** [PlanHubMe/PlanHub#303]
What could be doing this?
![Image](https://cloud.githubusercontent.com/assets/11902347/12186298/6ca9b5b4-b56f-11e5-86a1-d389e6cd5c60.png)

**Comment by thatoddmailbox** [comment]
@RobotXLabs `canvas.js`, something @em-p wanted me to add

**Comment by amazansky** [comment]
Oh. Hao do we fix it?
I don't think users will like getting that popup?

**Comment by thatoddmailbox** [comment]
@RobotXLabs FIXED
