### ISSUE TITLE
Object] Object] Object] Object] Object] Object] Object] Object] Object] Object] Object] Object] Moo!

### ISSUE THREAD

**Issue by amazansky** [PlanHubMe/PlanHub#319]
So the tab system is great and all, but if you try cycling through it, [Tab] [Tab] [Tab] [Tab] [Tab] [Tab] [Tab] [Tab] etc..., at the very end, it will say: Object (Text), then Object Object (Text), then Object Object Object (Text), and so on.
Why does it do this?

**Comment by medensqui** [comment]
@RobotXLabs ?

**Comment by thatoddmailbox** [comment]
@RobotXLabs What about it?

**Comment by RobotXLabs** [comment]
srry forgot a description writing nao

**Comment by thatoddmailbox** [comment]
@RobotXLabs Umm.....does this happen on both staging and prod?

**Comment by amazansky** [comment]
not sure about staging but ik prod

**Comment by amazansky** [comment]
[Wut.zip](https://github.com/PlanHubMe/PlanHub/files/88982/Wut.zip)
Daonload that

**Comment by thatoddmailbox** [comment]
@RobotXLabs it's weird because you don't have tab order set, so it should be default. Could you check staging?

**Comment by amazansky** [comment]
Still does it :(

**Comment by thatoddmailbox** [comment]
@RobotXLabs INVESTIGATION TIME

**Comment by thatoddmailbox** [comment]
Fixed!

**Comment by amazansky** [comment]
Yay! But maybe pull to stable?
Funny picture on stable
![object object](https://cloud.githubusercontent.com/assets/11902347/12340162/1dfdf650-bae7-11e5-9970-76fddf908f46.png)
