### ISSUE TITLE
My day deadline

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#35]
When do you think My Day should be available publicly? Probably after public release?

paging @medensqui @nywillb

**Comment by medensqui** [comment]
@thatoddmailbox Asap

**Comment by thatoddmailbox** [comment]
@medensqui So the same as public release?

**Comment by medensqui** [comment]
@thatoddmailbox if you can, and just note that it is slightly wip and will be added to

**Comment by thatoddmailbox** [comment]
Closing because we have a deadline!
