### ISSUE TITLE
MyDay Release Date

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#351]
Paging @PlanHubMe/coders, we need a date that we can say we will have MyDay by.

**Comment by thatoddmailbox** [comment]
@nywillb https://github.com/PlanHubMe/PlanHub/milestones

**Comment by willbarkoff** [comment]
@thatoddmailbox It won't come sooner. :frowning:

**Comment by thatoddmailbox** [comment]
@nywillb What?
