### ISSUE TITLE
Tags from subject names are uncolored in HW View

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#357]
![screen shot 2016-02-01 at 11 04 19 am](https://cloud.githubusercontent.com/assets/1904587/12722593/97a64bde-c8d3-11e5-85b0-743ee8bfb48c.png)

**Comment by willbarkoff** [comment]
@thatoddmailbox Thats easy to fix

**Comment by thatoddmailbox** [comment]
@nywillb but still is a bug.

**Comment by willbarkoff** [comment]
@thatoddmailbox Ok

**Comment by willbarkoff** [comment]
Should I fix right now

**Comment by thatoddmailbox** [comment]
@nywillb If you want to, sure! It would probably be somewhere in `hwView.js`.

**Comment by willbarkoff** [comment]
I know.

**Comment by willbarkoff** [comment]
HELP

**Comment by thatoddmailbox** [comment]
@nywillb ...
Maybe go on Slack.

**Comment by willbarkoff** [comment]
Okay.
