### ISSUE TITLE
Feedback should be somewhere we can all see

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#36]
Currently, sending feedback stores it in the database, but I must manually check it and no one else can see it.

It would be nice if all of us could see it. Maybe email feedback to all of us and/or something in CoursesPlus internal?

@nywillb @medensqui any ideas?

**Comment by medensqui** [comment]
@thatoddmailbox Typeform?

**Comment by thatoddmailbox** [comment]
@medensqui No, I meant to access the messages from the smiley and frowny face buttons. We can't do a Typeform for this because of the "send snapshot of webpage" feature, which is useful.

**Comment by medensqui** [comment]
@thatoddmailbox Ah true...

**Comment by thatoddmailbox** [comment]
I am going to put feedback on the mysterious Admin tab that has appeared for @medensqui and @nywillb

**Comment by medensqui** [comment]
@thatoddmailbox Yay
