### ISSUE TITLE
Live Support Chat

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#370]
Idea: So, someone is always on slack, right? What we can do is make an organization "PlanHub Support Chat" and put a [Slackin](https://github.com/rauchg/slackin) button on our site. When someone wants to live chat, they just push the button.

@thatoddmailbox I am assigning you because it needs server stuff. I can make the slack team though. You need to make a user on the slack team `@slackinviter`

**Comment by thatoddmailbox** [comment]
@nywillb You want the support to be a Slack chat? (for which they still need to register separately with an email, even if using Slackin)

**Comment by medensqui** [comment]
@nywillb IN GENERAL, (this is fine) DONT CHAT ON GITHUB CHAT ON SLACK

**Comment by thatoddmailbox** [comment]
@medensqui what?

**Comment by willbarkoff** [comment]
@thatoddmailbox I have early access to [nudgespot](http://www.nudgespot.com/). Would that work?

**Comment by willbarkoff** [comment]
@thatoddmailbox @medensqui [Chatio](https://chatlio.com/) would be best, but sadly, [pricing](https://chatlio.com/#pricing).

**Comment by thatoddmailbox** [comment]
@nywillb It looks like the part of Nudgespot you want to use [costs money](http://www.nudgespot.com/#pricing). (specifically, the "Retain" plan)

**Comment by willbarkoff** [comment]
@thatoddmailbox:
![screen shot 2016-02-09 at 1 25 56 pm](https://cloud.githubusercontent.com/assets/10969136/12926279/adf3540a-cf30-11e5-9ffe-3b17a912316a.png)

**Comment by willbarkoff** [comment]
@thatoddmailbox 

> Live Chat and Shared Inbox for your team to Collaborate & Acquire new users.

**Comment by thatoddmailbox** [comment]
@nywillb 
![screen shot 2016-02-09 at 1 28 44 pm](https://cloud.githubusercontent.com/assets/1904587/12926350/1697f1e6-cf31-11e5-8be0-7feb4fdf2aca.png)

> Customer Feedback

**Comment by willbarkoff** [comment]
@thatoddmailbox We already have a customer feedback program.

**Comment by thatoddmailbox** [comment]
@nywillb but I think that means the "customer sends you stuff" as opposed to "you send messages to people on the site"

**Comment by willbarkoff** [comment]
Here is what we need:

###### User:

> Ooohhh! How do I log out! I can't find the button anywhere!

_User clicks "Live Chat" button_

###### Me!

> How can I help you?

###### User:

> I do not know how to log out

###### Me!

> To logout, click your name in the top navigation bar, then click the "Log Out" button. 

###### User:

> Thanks!

_User has logged out_

**Comment by thatoddmailbox** [comment]
@nywillb if you want to

> Guide users through every step. Segment and message them contextually.

you have to get "Onboard + Engage", which is $49/mo

**Comment by willbarkoff** [comment]
WE JUST NEED LIVE CHAT!

**Comment by thatoddmailbox** [comment]
@nywillb BUT THE DIFFERENT PLANS CONTROL WHO STARTS IT: THE USER OR US

**Comment by willbarkoff** [comment]
@thatoddmailbox Ooohhh

**Comment by amazansky** [comment]
I KNOW!!!!!!!!!!!!!!!!!!!
So what we do goes like this:
We put secret button on our site, that when you press sends them a sweetalert that says "We'll get back to you soon", then PlanBot sends us a notification in some channel, then **we** click the start chat button, then we talk to user, and user is happy!
It's a bit of a process, but it could work.

**Comment by thatoddmailbox** [comment]
@RobotXLabs 

> Talk to Anonymous Visitors
> 
> Anonymous Visitors
> 
> Anonymous

:frowning: :frowning: :frowning: :frowning: :frowning: 

I'm not sure if there is another chat service that would better fit us, but Nudgespot's free plan seems to be for making sales on a website to potential customers, not helping existing ones...

**Comment by amazansky** [comment]
Ah k

**Comment by amazansky** [comment]
Found a few free ones (take a look):
https://www.purechat.com/
https://happyfoxchat.com/
https://linked.chat/

**Comment by willbarkoff** [comment]
@thatoddmailbox @RobotXLabs @medensqui I am leaning towards Happy Fox Chat. Pure Chat has restrictions on the number of chats per month, and LinkedChat says that it will eventually cost money. Would it be okay if I implemented?

**Comment by amazansky** [comment]
I think @nywillb is right. But we have to get permission from @thatoddmailbox b/c of server stuff
Actually I'll do it on staging.

**Comment by RobotXLabs** [comment]
Umm it wants phone #. Google Voice it?

**Comment by amazansky** [comment]
It wants a phone number...

**Comment by willbarkoff** [comment]
@RobotXLabs What about tawk.to? https://www.tawk.to/

**Comment by thatoddmailbox** [comment]
@nywillb @RobotXLabs slaask __doesn't work__
![screen shot 2016-02-17 at 9 25 45 am](https://cloud.githubusercontent.com/assets/1904587/13112431/a2716256-d558-11e5-9473-d0361c12a827.png)

(and when it does, it takes forever to load)

**_ATTENTION ALL STARTUPY PEOPLE_**
**_SOMEONE PLEASE MAKE A LIVE CHAT THING THAT:_**
- is free
- works with Slack
- actually works
- doesn't suck
- doesn't look ugly

**Comment by thatoddmailbox** [comment]
![screen shot 2016-02-17 at 9 36 01 am](https://cloud.githubusercontent.com/assets/1904587/13112690/e92950cc-d559-11e5-94f8-e914f9792510.png)

**Comment by amazansky** [comment]
BUT WHAT ABOUT HAPPYFOX CHAT

**Comment by thatoddmailbox** [comment]
@RobotXLabs didn't it need a phone number for support? and does it do Slack?

**Comment by amazansky** [comment]
Yes, and yes. But can we not use google voice or something? Or an autogenerate random number thing?

**Comment by thatoddmailbox** [comment]
@RobotXLabs hao does Google Voice help? and also some sketchy random number thing would be annoy depending on what they use it for. Do they say wheye they want a phone number?

**Comment by thatoddmailbox** [comment]
@RobotXLabs 
![screen shot 2016-02-17 at 2 50 09 pm](https://cloud.githubusercontent.com/assets/1904587/13122599/c79a44b2-d585-11e5-986b-8c855c9eeb4c.png)

:disappointed:

**Comment by thatoddmailbox** [comment]
@RobotXLabs oh wait, nvm. found the problem

![screen shot 2016-02-17 at 2 51 02 pm](https://cloud.githubusercontent.com/assets/1904587/13122624/e786c764-d585-11e5-89ee-e0da879b1787.png)

That's a bit of a problem if we want the chat widget to work inside Dalton...

**Comment by amazansky** [comment]
Yeah I guess... Or ask them to unblock, its relatively easy for them.

**Comment by willbarkoff** [comment]
Closing because tawk.to was implemented
