### ISSUE TITLE
Kinda sorta a bit ishy weird?

### ISSUE THREAD

**Issue by amazansky** [PlanHubMe/PlanHub#374]
Just look
![screen shot at a random point in time](https://cloud.githubusercontent.com/assets/11902347/13027402/f09862fc-d21c-11e5-9ac9-403b93dbcef7.png)

**Comment by amazansky** [comment]
Btw its the alert for HW View

**Comment by thatoddmailbox** [comment]
@RobotXLabs wut O_o. Does that happen several times or only once?

**Comment by amazansky** [comment]
Nope only this morning. Just checked, it worked. Strange.
