### ISSUE TITLE
Organization

### ISSUE THREAD

**Issue by c20ms1** [PlanHubMe/PlanHub#375]
# Javascript Folder

May I suggest that you move all of your javascript into a dedicated js folder? It'd be much easier to look at and organize than the splattered files right now.

**Comment by thatoddmailbox** [comment]
@c20ms1 It's a bit confusing because we use JavaScript both on the server and the client side. All client-side JavaScript is under `public/js/`. Server side JavaScript that serves webpages and API stuff is under `routes/`, and the JavaScript files in the root directory tie everything together.

**Comment by c20ms1** [comment]
Thanks, that explains it pretty well. At least this will be here for future confused organizers.
