### ISSUE TITLE
Make a new tag called presentation?

### ISSUE THREAD

**Issue by amazansky** [PlanHubMe/PlanHub#377]
Fairly self-explanatory...

**Comment by thatoddmailbox** [comment]
@RobotXLabs have you responded?

**Comment by amazansky** [comment]
No, I will.

**Comment by thatoddmailbox** [comment]
@RobotXLabs Ok. plox use planhub emailz

**Comment by amazansky** [comment]
I will.

**Comment by medensqui** [comment]
@RobotXLabs Have u responded because I will if you haven't

**Comment by willbarkoff** [comment]
@RobotXLabs Has.

**Comment by amazansky** [comment]
@medensqui Sorry, forgot to BCC you.

**Comment by amazansky** [comment]
Think this is done! We just need a pull to stable... Until then, we can't email the feedback-er.

**Comment by willbarkoff** [comment]
We can email that we have written all the code for it. Also, this is not included in #380.

**Comment by thatoddmailbox** [comment]
@nywillb yes, it is, and also I don't think the person who sent the feedback cares if it's coded, they care if it works

**Comment by willbarkoff** [comment]
I guess....

**Comment by amazansky** [comment]
Agree with @thatoddmailbox. We need to get it out onto production server. I set a goal for within a week of the feedback which is... the 24th. Here is stuff we need to do
- [x] Code
- [x] Put on staging
- [x] Test for workyness and shinyness (QC)
- [x] **Pull request to real PlanHub**

**Comment by thatoddmailbox** [comment]
@RobotXLabs Done! You should probably be the person to send the email confirming it.
