### ISSUE TITLE
Check things off in HW View 

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#38]
You should be able to check things off directly from HW view, rather than going back and forth from the planner.

**Comment by medensqui** [comment]
@thatoddmailbox Or what about being able to check off in my day

Sent from FirstClass with my iPhone

**Comment by thatoddmailbox** [comment]
@medensqui Like check off the entire due tomorrow column? Idk how useful that is, but we could add it.

**Comment by medensqui** [comment]
@thatoddmailbox No my point is so,

In My Day, to track time taken and to adjust schedules accordingly, we need to be able to track when the assignment was supposed to start (easy) and when the student finishes it (aka when they press the done button)

**Comment by thatoddmailbox** [comment]
@medensqui OOOHHHHH!

If we wanted to be really magical, we could average past times.

So like when it asks for the time to, say, read the day 4 reading in history, it will say "on average, readings in history take you about " and then however many minutes it is!

**Comment by thatoddmailbox** [comment]
This is done! (not on stable yet, though)

**Comment by willbarkoff** [comment]
How do you do this?

**Comment by thatoddmailbox** [comment]
@nywillb 

> (not on stable yet, though)

Checkboxes appear next to the homework items. You can disable them in the preferences panel.

**Comment by willbarkoff** [comment]
@thatoddmailbox The checkboxes are very pixalated.

**Comment by willbarkoff** [comment]
@thatoddmailbox It is not shiny

**Comment by thatoddmailbox** [comment]
@nywillb go figure out to make checkboxes larger without pixelation and cross-platform. When you do, come back here and I will do the magic hexr dance.

**Comment by willbarkoff** [comment]
http://codepen.io/bbodine1/pen/novBm

**Comment by thatoddmailbox** [comment]
@nywillb That is not using native controls and will look funky. But still, __~~~magic hexr dance~~~__.

Make another issue though, as this is finished.
