### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by amazansky** [PlanHubMe/PlanHub#385]
How great would it be if we could have analytics?
(Answer: Super great)
Opinions, anyone?

**Comment by willbarkoff** [comment]
@RobotXLabs Piwik is something we have been putting off for _a really long time_.

**Comment by thatoddmailbox** [comment]
@nywillb shhhhh

@RobotXLabs I should probably set up a Piwik thing, similar to what is there for the coursesplus site.

**Comment by amazansky** [comment]
Okay @thatoddmailbox, set a goal for yourself. **THAT IS NOT MORE THAN A WEEK AWAY** To do piwik by. Please. Sooner is better.

**Comment by willbarkoff** [comment]
@thatoddmailbox Lets just do it now.

**Comment by willbarkoff** [comment]
@thatoddmailbox @RobotXLabs It takes like five minutes

**Comment by amazansky** [comment]
Good idea.

**Comment by thatoddmailbox** [comment]
@RobotXLabs @nywillb just so you know&mdash;if you aren't seeing yourself being tracked, make sure you don't have something like uBlock or Ghostery or DNT enabled.

**Comment by amazansky** [comment]
How can I view the analytics?

**Comment by amazansky** [comment]
Yay done

**Comment by willbarkoff** [comment]
@RobotXLabs How?

**Comment by thatoddmailbox** [comment]
@nywillb piwik was added and working
