### ISSUE TITLE
How much HW do I have?

### ISSUE THREAD

**Issue by amazansky** [PlanHubMe/PlanHub#387]
When I enter some HW into planner, then go back to overview because I don't want to count out my assignments, the value that is there is the one that was when I loaded the page.

In other words, make it update every time the tab is loaded.

**Comment by thatoddmailbox** [comment]
@RobotXLabs This is already the case... Are you sure you are putting it on the right day? It only checks the next day.

**Comment by amazansky** [comment]
Ooh. K got it.
