### ISSUE TITLE
GET RID OF TAWK

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#399]
@nywillb Y DO WE NEED TAWK NU ONE USES IT

WE'RE A WEBSITE WITH 70 USERS AND 5 PEOPLE WORKING ON IT. 

By the way, I'm using github because @nywillb is never on Slack.

**Comment by willbarkoff** [comment]
@medensqui I dunno.

**Comment by medensqui** [comment]
@nywillb Then, why do we have it?
