### ISSUE TITLE
Un-alting a planner box

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#402]
You can replace the contents of a box with "none" by holding alt and clicking on a box on the planner. However, if you replace the text of a box with "none" and try to undo that by alt-clicking again, it will wipe the box. What we should do is replace the text with what was there originally, so accidental clicks won't destroy data.

**Comment by amazansky** [comment]
Or just get rid of the alt feature?

**Comment by thatoddmailbox** [comment]
@RobotXLabs but it's useful...

**Comment by amazansky** [comment]
I didn't know about it until you first made this issue...

**Comment by thatoddmailbox** [comment]
@RobotXLabs it was added by @willweinstein a while ago. I was using it when I realized that I should make this issue.

**Comment by amazansky** [comment]
Okay? But shouldn't it be easy?

**Comment by thatoddmailbox** [comment]
@RobotXLabs ...yes...

**Comment by amazansky** [comment]
**Just do it**!

**Comment by willweinstein** [comment]
@thatoddmailbox remind me and ill `hexy.doitlater`

**Comment by thatoddmailbox** [comment]
@willweinstein YOU HAVE BEEN REMINDED
