### ISSUE TITLE
Hi Rultor!

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#403]
@rultor hello

**Comment by thatoddmailbox** [comment]
@nywillb what?

**Comment by willbarkoff** [comment]
@rultor hello

**Comment by willbarkoff** [comment]
@thatoddmailbox See!

**Comment by willbarkoff** [comment]
@rultor merge

**Comment by thatoddmailbox** [comment]
@nywillb 

> First, we install all Ruby gems required for Jekyll (this is how this website is built). Then, we deploy the system to CloudBees. Then, we deploy the site to Github Pages.

We don't use Ruby, Jekyll, CloudBees, or GitHub Pages.

**Comment by willbarkoff** [comment]
I know

**Comment by willbarkoff** [comment]
But it is still fun.

**Comment by thatoddmailbox** [comment]
@nywillb Then what is it for?

**Comment by willbarkoff** [comment]
I dunno.

**Comment by willbarkoff** [comment]
@rultor close
