### ISSUE TITLE
EU Cookie Compliancy

### ISSUE THREAD

**Issue by amazansky** [PlanHubMe/PlanHub#407]
1. Why are we aiming to be cookie compliant in the **EU**?
2. The alert blocks some of the text at the bottom of http://planhub.me/privacy if you don't accept and choose to "read more".

**Comment by amazansky** [comment]
1. Paging @nywillb 
2. add some room to bottom of page? (only problem I could see is if what about other devices where spacing is weird)

**Comment by thatoddmailbox** [comment]
@RobotXLabs 

> only problem I could see is if what about other devices where spacing is weird

shh 13 inch screens with 1366x768 resolution are the only things that exist phones what are phones
