### ISSUE TITLE
Move authentication thing to not use Schedules

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#425]
Currently, it tries to sign you in via Schedules, but during the summer, Schedules is closed by giving an "invalid credential" message to all sign in attempts. This would disable MyHomeworkSpace over the summer. 

We should find something else to use. Possibilities are:
- reports? Would be a bit weird though, and they might shut that down because students aren't supposed to log in, even if they only go to a blank screen.
- courses? I think it also just returns "invalid login, try again" over the summer.
- the thing daltonplanner uses? I __really__ do not want to do this because it seems pretty sketchy, and the credentials are passed as GET parameters, which means they are probably logged somewhere.
- bug New Lab for something? They had something on sandbox, but it's gone now...

@MyHomeworkSpace/coders please let me know if I forgot something.

**Comment by thatoddmailbox** [comment]
Marking as high priority because no one likes failed logins.

**Comment by thatoddmailbox** [comment]
Other possibilities maybe?
- owncloud - would be incredibly hacky, and they could update it, which would break logins
- forum - same as above
- bug New Lab for a magic sso thing with whipplehill - would be nicest, but probably most difficult because SAMLy things
- ???

**Comment by willbarkoff** [comment]
Reports leaves a 505 for middle schoolers, so we can strike that one.

**Comment by thatoddmailbox** [comment]
@nywillb It seems like they fixed it; it used to let students log in, but would only take them to a blank page.

**Comment by willbarkoff** [comment]
![screen shot 2016-06-08 at 11 53 37 am](https://cloud.githubusercontent.com/assets/10969136/15901090/e32463a6-2d6f-11e6-8d74-2ca1f8d7ee76.png)
_(Yes, I did double check my username and password)_

**Comment by thatoddmailbox** [comment]
@nywillb 

> It seems like they fixed it

**Comment by willbarkoff** [comment]
@thatoddmailbox schedules.dalton.org goes down over the summer, so should we just write an announcement that says something like "MyHomeworkSpace will be unavailable from Thursday, June 16, 2016 (Arch Day) to Wednesday, September 7th, 2016 (First day of the 2016 School Year). We apologize for any inconvenience. Have a great summer!"

**Comment by thatoddmailbox** [comment]
@nywillb but the point of this issue is to avoid that. What if someone wants to plan out their summer, or has important dates written down?

**Comment by willbarkoff** [comment]
Maybe we could generate an ICS for them?

**Comment by willbarkoff** [comment]
how did you close this?

**Comment by amazansky** [comment]
@thatoddmailbox: Hacky hacky...

**Comment by thatoddmailbox** [comment]
@nywillb In commits b03b605 and 94fdab0?
