### ISSUE TITLE
Some sort of easter egg or hidden feature

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#44]
This is _extremely important_. If we do not include this, PlanHub will never succeed.

But it can't be a snake game.

...

@medensqui @medensqui

**Comment by thatoddmailbox** [comment]
That second mention should be @nywillb

**Comment by medensqui** [comment]
@thatoddmailbox Y?

**Comment by medensqui** [comment]
@thatoddmailbox How about the spinny hex security hole?

**Comment by willbarkoff** [comment]
@medensqui @thatoddmailbox What about a pacman type of thing? Or we could have the Konami Code change the background color. See http://www.theverge.com/2013/5/17/4340740/google-hangouts-easter-eggs-include-shy-dinosaurs-and-stampeding

**Comment by thatoddmailbox** [comment]
@nywillb Obviously we make the Konami code trigger pacman that, when you win, changes the background color and spins the page.

**Comment by medensqui** [comment]
@thatoddmailbox NO, SPINNY HEX BUG
_@nywillb modified this comment for better english syntax_

**Comment by thatoddmailbox** [comment]
@medensqui No as in "no, don't do this?" or no as in "no, do this instead?"
_@thatoddmailbox @nywillb updated the above comment so that it answered this_

**Comment by medensqui** [comment]
@thatoddmailbox DO IT

**Comment by willbarkoff** [comment]
@thatoddmailbox that is awesome. But if you type /ponies into the planner box, it should make a ponies go across the screen.

**Comment by medensqui** [comment]
@nywillb IT DIDNT WORK ALSO GRAMMAR

"IT SHOULD MAKE A PONIES" "IT SHOULD MAKE A PONIES" WHAT? TSK TSk

**Comment by willbarkoff** [comment]
@medensqui Try it in google hangouts. It will explain everything.

**Comment by thatoddmailbox** [comment]
@nywillb @medensqui 
For the lazy, I found an image online: (not my phone)
![ponies](http://4.bp.blogspot.com/-PpgbB4J5vBs/U3MFlBNUjtI/AAAAAAAAArY/Q59ukeILqcM/s1600/hangouts-easter-egg.jpg)

**Comment by willbarkoff** [comment]
@thatoddmailbox @medensqui Your idea is the best:

> @nywillb Obviously we make the Konami code trigger pacman that, when you win, changes the background color and spins the page.

except for one revision. Every time you get a point it does that stuff. This is ready to implement.

**Comment by willbarkoff** [comment]
@willweinstein Did you implement this?

**Comment by willweinstein** [comment]
@nywillb the spinny thingy? yes. type in ey.hex(u);;;;; and click away. **WARNING** THE SPINNY THING IS HARD TO GET RID OF. TO GET RID OF IT DELETE THE CODE AND RELOAD THE PAGE. **I AM NOT RESPONSIBLE FOR ANY PERMANENT SPINNYNESS**

**Comment by em-p** [comment]
Obviously this must be re-opened
duh
cause memes

**Comment by amazansky** [comment]
Umm @em-p 
I'm not sure of any need for memes right now. @PlanHubMe what do we think?

**Comment by willbarkoff** [comment]
@RobotXLabs Reopening because we do need more easter eggs (but you are right about the memes)

**Comment by amazansky** [comment]
WE NEED MORE EASTER EGGS

And okay about the memes

**Comment by thatoddmailbox** [comment]
Closing because this issue is sort of vague. If you really think there should be another easter egg, please make another issue for it.
