### ISSUE TITLE
After you login, it's just a blank screen

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#47]
Let's have some interesting line at the beginning or just go to overview

My idea for overview:
My Day - What you should be doing right now
Planner - What you have next in each subject
HW View - How many assignments you have in each category

**Comment by medensqui** [comment]
paging @thatoddmailbox @nywillb

**Comment by willbarkoff** [comment]
@medensqui You know you can write "@PlanHubMe/idea-thinkers"

**Comment by willbarkoff** [comment]
also @PlanHubMe/idea-thinkers Please add me to your team.

**Comment by thatoddmailbox** [comment]
@medensqui It should be going to Overview. Which right now just shows the date.

**Comment by thatoddmailbox** [comment]
@nywillb You can click "Join". Go to the organization page, click Teams, and then Join next to idea thinkers

**Comment by medensqui** [comment]
@thatoddmailbox Studer look at my My Day UI idea

**Comment by thatoddmailbox** [comment]
@medensqui I'M TRYING THERE ARE SO MANY GITHUB ISSUES AAAAAAAGGGHHH

**Comment by thatoddmailbox** [comment]
@medensqui Is this still true, or does it now show Overview, which is just the date.

**Comment by medensqui** [comment]
@thatoddmailbox It works
