### ISSUE TITLE
Public Beta

### ISSUE THREAD

**Issue by willbarkoff** [PlanHubMe/PlanHub#48]
We should release a public beta with **a slow rollout**.

**Comment by thatoddmailbox** [comment]
@nywillb The deadline for it being publicly available in some form is Thursday or maybe Friday.

However, between Thursday and now, we could slowly add more people to the whitelist, if that is what you mean.

**Comment by thatoddmailbox** [comment]
Closing this because it is publicly released and we have #143 done too.

**Comment by willbarkoff** [comment]
@thatoddmailbox We should have a public beta channel so that people can test things. See PlanHubMe/beta.planhub.me and the Beta branch.

**Comment by thatoddmailbox** [comment]
@nywillb could people not use staging.planhub.me?

**Comment by willbarkoff** [comment]
@thatoddmailbox No, because it staging is not partially stable.

**Comment by medensqui** [comment]
@thatoddmailbox But the beta is for TESTING NOT FOR USING. THE WHOLE POINT OF THE BETA IS THAT IT IS NOT STABLE!

**Comment by medensqui** [comment]
@nywillb

**Comment by thatoddmailbox** [comment]
@nywillb also a beta would suck up more server resources that could be better spent on the stable site. though mainly what @medensqui said.

**Comment by willbarkoff** [comment]
@thatoddmailbox Good Point. ~~Public Beta~~
