### ISSUE TITLE
Are we putting this on GitHub yet?

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#5]
@thatoddmailbox

**Comment by thatoddmailbox** [comment]
@medensqui I will, just let me fool with the domain first.

**Comment by thatoddmailbox** [comment]
@medensqui oh btw it now works! you get an under construction page, but it works!

**Comment by medensqui** [comment]
@thatoddmailbox YAY

**Comment by thatoddmailbox** [comment]
Done!
