### ISSUE TITLE
Multiple events on one day

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#51]
It should be possible to put multiple events on one day and have them counted separately.

**Comment by medensqui** [comment]
@thatoddmailbox Agreed!

**Comment by willweinstein** [comment]
@thatoddmailbox why not have the tiles marked by putting /[insert title]/ instead of being the first word in the box
this would allow users to put spaces in titles and to have multiple titles thus multiple events in one day

**Comment by thatoddmailbox** [comment]
@willweinstein No, because they still need to be counted as multiple events for things like HW view and my day.

**Comment by willweinstein** [comment]
@thatoddmailbox yeah, you would do /hw/ this hw assignment /hw/ second hw assignment

**Comment by willweinstein** [comment]
@thatoddmailbox this isn't important for public release, its useful but is no where near necessary

**Comment by thatoddmailbox** [comment]
@willweinstein yes it is important because there have been many complaints and things from beta testers, and these complaints would get worse on release.

**Comment by willweinstein** [comment]
@thatoddmailbox FINE

**Comment by willweinstein** [comment]
@thatoddmailbox SKYPE?

**Comment by thatoddmailbox** [comment]
@willweinstein 
&nbsp;

H̢̨̨̨̢̡̨̡̛̛̙̖̝͈̱̠̤̻̮̣̗͕̤̳̩̗͎͚̲͎̰̞̬͖͓̬̳͍͍̪̳̜̠̻̳͉̹͖̻͎̖̦͙̰͍̬̝̮͙̗̤͕̼̯̣̳̱͎̠̥̮̩͎̹̦̦͕͕̝̬̩͎̞̗̹͈͎͎̹̭̦̼̆̂͂̇͆̂̿͂͑́̒̽͌̐́͛̀̏̒̇̏̾̃͒̌̃͂̂́̀͌́̾̂̋̔̃̀̔͛̒͒͑̂̒̀̒̀̉̈̍͛̽̅̔͂͆͌̇̊̐͗̊̓̒́͗͛̒̐̉̀̓̈̋̿͊̈̚͘̚͘͘͘͘͜͜͝͝͝͝͠͝͠ͅͅë̢̡̧̡̢̨̨̧̛̛͙̮̬̝͚̪̖̫̭̼͇͓̩͚̰̱̤̼͔̹̫̜͎̫̗̼̥̫͖̰̭̘̬̦̺̫̟̫͉̳̥̗͖̲̩͇̰̺̭̮͖͙̥̟̱̬͇̦̝͙̜̠̻̩̬͕̹̖̜̙̝͔̮̫̩̺̜͍̲̝̫̪̩̘͔̖̭̇́̌̑̔́̉͐͒͌͆͆͋̀̾́̈́̍͐̀̄͒̏͐̔̄̒͒̓́̔̋͌̓̄̋̈̈̔͊̿̌̾͗̿̽̄̊̃̓͌͐̓̀̇̀̀̉͌̅̅́́́̐͗̒͂͗̓̎̃̔̒̐͐̿̀̎̈́̊͘͘͘̚̚͝͠͠l̡̧̢̧̧̡̯̮͈̱̞̻̫̠̲̻͎̼̮̩̟̱̖͚̤̖̩̮̗̭̤͖̥̘̠̯̳̜̠̫̦̯̰̻̳̗͍̯͎̘͇̹̭͔̭̦̹̤̺̝̞̝͎̰͓̺͚̘̳̰͎̭̗̘̘̜͎͙̹̩̰̪̣̻̞͍͙͇͔̖̫͖̳̘̟̍̀͗̾̉̽̐̔̀̾̎̍̾̑͌͊̈́̒̇̂̌̍̑͐͒̈́͑̇͑̄̽̓̐̊͋͛̎̍̈́͊̍̇̈́͛̒̉̉͆̊̈́̄̇̿̐̌̌̄͒̈́̈́̊͂͌̾̍̍͂̽́͛̿̀̈́̌̃̄͋̽̅̿̒̎̈́̀̔̍͘͘͘̚͜͜͜͝͝͝͠͝͠ͅl̡̢̢̧̡̡̨̨̨̛̜̯̰̲̼̪̞̖̤͍̦̤̲̖͍̯̙͍̱͚̫̦̘̫̙͍̙̺̟̜̯̜̥̪̖͔͖̱̭̩͙͕̻͉̯̞̻̼̪̫͎̺͕͚͓͉͖̪̩͇̠̹̞̖͚͚̪͓̤͍̠̮̦̦̫̳̜̫̰̪̀̇̀̇̇̋̍̐̓̓̑͐̏̈̆̆̓̈́̇̉̉͑̅͋̎̔͆̀̈́͊̈́̏̾̄̄͛̊̉̀͗͑̑̽͗̾̊̂̈͗̒̿̊͆͊̃́̎̀͋̾͗͂̓̈́͑̾͗̍̎̆̎͐̐̀̔̆̌̉̊̎̒͘̕̕̕̕̕͘̚͘̕̚͜͜͜͜͠͝͠͝͝͝͝ͅơ̢̢̧̛̯̤̼̟̺̼̪̰̦͔͎̖̮̞̜̠̼̣̘̝̮͎̲͚͙̮̱̜̣̟̲̩̝̖̫̠͇͓̖̣̙̜͉͔͔̺̳͔̭̮̹̮̖̹̣̝͎̪͓̙̹͔͈̗̬͉̪̳̦̦̯͔̱̞̟̬̭̖̤̪͖̙͙̣̝͉̟̐͂̉̆̅̃̏́͊͌͆̈́̋̀̄̐̌̓͂̍̾̒̾̅̈́̓̾̒͒͌̐̌̌̽̾̇́̌͒̄̐̾̍̿̉̿͛̃̏̆̾͋͋̃̀̋̓̀̉̔̽͂̃̌͗̈́͆̒̋̆̎̍͊͗̇̄̎̇̓̍͗̄̐͘͘͘̕͝͠͝͝͝͝͠ͅͅͅͅ!̧̡̢̢̨̛̛̛̛̛͉̰̟̯̯̙̫̺̞̯͍͔̖̺͚̭͓̜̰͚̱̫͎͔̙̞̻̼̝͚̪̞̪̙̖̤̖̯͈̮͎̻̰̙̘̯̱̤͖̗͈̞̺̟̝͇͚̺̲̜̦̼̘̦̦̥̯͍̘̭̹̠̬͓̘̗̜̻͎͉̩͈͚͈̫̈́̓̅̔̅̌͗́͒̍̌̏̐̇̋͛́̐͋̽͒̂͗̈́̉͐̿̂̃͊͑̌̈̂̉͂͆̅́͋̑́̾̉̈́̆͂̔̏̅̈́̿͂͛̏̇̈́̐̏̀̓̌̍̉̍̌̿̊̈́̃̅̒̑̌͌̊̊̀̏̒͌̕̚̕̚͜͜͜͝͝͝͝͠͠͝ͅ

**Comment by willweinstein** [comment]
@thatoddmailbox how do you do that?

**Comment by willweinstein** [comment]
@thatoddmailbox ha comments that come after cover it!

**Comment by thatoddmailbox** [comment]
@willweinstein m̡̢̧̢̱͚̻͖̣͈͖̖̥͎̺̬͕̝͈̪͉̬͓̲͒̋̈̋̔͆́̎̊̈́̂͂̍̇̂̾̆̓̈́̕̕͘͝͠͝ą̧̦̩͓̻̞͍͖͔̮̣͉̤̜͚̘̮̖̩̖͎̠̘̖̈́̍̆̂͂̊̊́̈́̾̈̎͌́̽̂̾͑̔̌͌͂̚̚͠g̢̛̹͚̹͉͈̟͓̝̬͍͇̳̩̬̼̲̹͙͎̯̰̞̣͋̈́̉̃͂̂̈́̀͂̏̋̌̐̾̑̑͋̔͊͘̕͘͜͝͝i̧̨̨̢̛̛͈̗̪̺̻̫͈̰͙̮͇͇̝̰̙̖͚̦̩̩̓͌̀̾̿̾̈́́͗̋̑̄͋͐͗̉̓͒̀̕̕̕͝ͅc̨̧̛̛̮̬̝̦̳̩̫͍̭̳͖̖̰̹̘̖̗̲̬̲͚͊̏̅́̈̐̂̃̐̊̑̈̓͂̈́͛̿̿̈́̏̄̚͜͜͝

**Comment by willweinstein** [comment]
@thatoddmailbox TELL ME

**Comment by thatoddmailbox** [comment]
@willweinstein :̡̧̛͓͇̫̫͙̮̝̱̠͈̭̱̺͓͖̫̪̫̰̤̗̻̿͒̈̒̆́̈́̐̅͌͌̀̏̉̈́͂̃̓̇̌͆͠͝ş̢̨̯̝̳̼̝̫̜͖͍̩̜͓̜͓͚̟̪̯̮͓̼̅̈́͊͒̄̋͊̈́̾͗̿̓͂̇̂̂͗͊̉̓̃̚͘̚͠ţ̛͇͉̪̬̜̠̝͓̺̤͔̙̦̫̦̮̤̩͚͇͇͈͊̽̉͋̔̋̾̈́̍̏̅͆͗̄̐͒̊̋̉́̓͂͜͜͝͝ừ̡̨̙̥̤͙̗̣̲̦̩̫̱̤̯͇̱͉͎̮̺͎̪̋̿̄͛́͐̂̀̈́͐͗̔̋̀̂̋̓͂̕͘͝͝ͅͅc̡̧̞̖̘̠͚͕̘͕̠͍̤̤͇͖̫̝͈͚̺͐̄̏̐̅̌̽̈́̈́̏̂͊̑̆̃̓̏́͑͋̃́̕͜͝ͅͅͅk̡̜̩͉͖͇͇̣͙̬̙̱͕̼̲̖̘̣̬̱͎̠͌̒̈͒͋̒͊̒̐̈́͗̓̽̓͑̃͆̈̽̐̄͌͘͘͜ͅ_̨̛̳̥̫͇͈͈̤̱͇̝̖̺̬̙̣͈̦̰̞̳̞̗͔̯̈́̇͛̏̃̐̓̇̂̈́̽̓̓̓͋̂̈́͗͒͊̈͘͝͝ớ̡̝̥͙͈̳͎̼͖̬̝͈̥̪̯̣͈͇̝̻͉̞̼̫̍͑͑̊̄̓̄̀̂͗̔́͆̈͋͆̎̔̆̽̕̚ǘ̢̢̢̞̣̻̰̪̪̘̮̩̘̰̙̫̯͍̤̙̜͉̙́̃͊͌̃̅̈́̌̽̂͋̀̑̂̓͑̐̐͛̂̂̕͜͝͠ͅţ̢̧̢̦̦͖̬̝͖͙̜͈̰̬͇̲̩̙̙̘̰̲̟̽͑͌̒̏̈́͑̐̔̀̿̽̍̈́́̋̎͂̆̆̾̕͝͝͝_̗̙̪͉̤̘͖̱̙̭͕̯̝̮̳͖̟͇̪͈̟̜̖̀̉̊̌̍̿̀͐͌͗̓́̉̾̓̓̓̇̔́͌̿̕͠͝ͅt̨̮̻͈̲͈̫̳͖͔̘͚͙͎͎͍͉̱̺͖̥̗̟̭̽̽̌̈́͗͋̒͂̈̽̓̾̅̈́͌̒̋̒̀̌̑̒̌́o̧͈̜͙̯̰͔̦̻̗̮͎͕̩͖̺̦̱͍̱̹͍̙̓̿̔̀̉̀̍̾͛̆̒̓̎̍͗͋͛̄̄̕̕͜͝͝͠͠ņ̨͎̗̳̥̳̻̦̪̠̳̜̼͈̣̙͕͍̪̣͚͖̓̆͗͋̈́̎͗̒̐̆̉̽̈́̔̏̈́͒͒̽̇͒̕͜͝͝ǵ̭̜̣̘͍̗͕͈̣̫͇̺̳̜̮͇͍̪̠̙̹͙̥̿̃̒͒̑͌̊̽͒̓͆̎͐̂̂̂̈̑̚͘͘͝͠ͅu̢͕͕̝͍̞̰͍̩̪͈͈͉̩̙͍͔̜̮̱͉̲̝̍̌̈́͑͆̈͊͛̄̎͌͛̉̔̈̔̚̕̕͜͜͝͝͝͝͝ę̡̛̥̱̣̟͓̦͓͍̺̗̹͚̘̭͚̖̣͚̟͎̙͓̍͊̑̽̌̍̊̓̂̉̽̈͂̐̍̊̃̿͑͂̅̍̚:̧̧̛̛̦̟̖͚̟͎̬͓̥̬̦̞̩̮̞̫̮̳̙̬̙̿̇̊̂͋̔͗̐̂͛͗́̾̿͗̃͋̏̽́͘͜͝͠

**Comment by willweinstein** [comment]
@thatoddmailbox ɹǝpnʇs noʎ ƃuıɥɔʇɐʍ ǝɹɐ ǝʍ

**Comment by thatoddmailbox** [comment]
@willweinstein (removed funky text because it made github slow)

**Comment by thatoddmailbox** [comment]
This has been done as of 7692f01 to some degree. It is a bit buggy and could be improved on, but it _works_.

Closing this issue and merging it into stable...
