### ISSUE TITLE
Move sections on planner

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#66]
The move button should work.

**Comment by medensqui** [comment]
@thatoddmailbox No duh. Idk if we're ready to release on Thursday

A lot of things haven't been started/aren't done

**Comment by thatoddmailbox** [comment]
@medensqui Idk if we can make Thursday/Friday, but we have _something_ that is at least almost on feature parity with daltonplanner.org (minus broken reminder buttons and colors, which we replaced with tags). 

I think we should focus on My Day after making the planner work well.

**Comment by medensqui** [comment]
@thatoddmailbox True

**Comment by willweinstein** [comment]
@thatoddmailbox how does the planner know what order to put them in? if it is just a number, we could implement a simple system where you just switch one and the other instead of coding a tiring drag system where it has to move all if you move one

**Comment by willweinstein** [comment]
@thatoddmailbox also, what is this: "duplicationstartshere_dontyouseethis?" i found it on my planner

**Comment by thatoddmailbox** [comment]
@willweinstein The problem isn't how to switch the sections, but how to make them draggable

**Comment by willweinstein** [comment]
@thatoddmailbox then make them switchable and save the draggable part for after the public release

**Comment by willweinstein** [comment]
@thatoddmailbox i dont completely understand this but it seems pretty legit:
http://www.w3schools.com/HTML/html5_draganddrop.asp

**Comment by thatoddmailbox** [comment]
@willweinstein but it doesn't let you reorder stuff, just move them around.

**Comment by willweinstein** [comment]
@thatoddmailbox but could you check where they were moved to and query that as their id or something and arrange them by id every time you load?

**Comment by thatoddmailbox** [comment]
@willweinstein yes, you could change their `sectionIndex`column value
