### ISSUE TITLE
Stuck on loading screen

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#72]
For like 3 minutes

![screen shot 2015-10-27 at 9 08 30 am](https://cloud.githubusercontent.com/assets/12429395/10758867/657f1856-7c8a-11e5-94c4-4b7adcfd9442.png)

**Comment by thatoddmailbox** [comment]
@medensqui !!!!!

Did you try reloading? I broke some things first period and you should reload the page. If that does not work, go to planhub.me, sign out, and sign in again.

**Comment by medensqui** [comment]
@thatoddmailbox Didn't work

**Comment by medensqui** [comment]
@thatoddmailbox Maybe you forgot to merge?

**Comment by thatoddmailbox** [comment]
@medensqui It's working for me. Right click and inspect element. Go to "Console" and see if there are any errors.

**Comment by medensqui** [comment]
@thatoddmailbox Here ya go

![screen shot 2015-10-27 at 9 18 15 am](https://cloud.githubusercontent.com/assets/12429395/10759079/b1108916-7c8b-11e5-92ed-6175cfc3c00c.png)

**Comment by thatoddmailbox** [comment]
@medensqui Ok. Go to the network tab.

**Comment by medensqui** [comment]
@thatoddmailbox And do what?

**Comment by thatoddmailbox** [comment]
@medensqui Take a screenshot.

**Comment by medensqui** [comment]
@thatoddmailbox Here
![screen shot 2015-10-27 at 9 19 43 am](https://cloud.githubusercontent.com/assets/12429395/10759108/e2a14b50-7c8b-11e5-8f45-4950ed17a83a.png)

**Comment by thatoddmailbox** [comment]
@medensqui Leave the network tab open and reload the page

**Comment by medensqui** [comment]
@thatoddmailbox 
![screen shot 2015-10-27 at 9 20 38 am](https://cloud.githubusercontent.com/assets/12429395/10759136/0552dc72-7c8c-11e5-8168-0b361892b6ed.png)

**Comment by thatoddmailbox** [comment]
@medensqui Type in to "Filter" the word "get". Click on the last request. Screenshot what opens

**Comment by medensqui** [comment]
@thatoddmailbox Here's the start, tell me if you need more
![screen shot 2015-10-27 at 9 22 10 am](https://cloud.githubusercontent.com/assets/12429395/10759173/3dde8898-7c8c-11e5-8fd7-8c237991e54c.png)

**Comment by thatoddmailbox** [comment]
@medensqui I AM STUPID I MADE A FIX THANK YOU FOR HELPING HOLD ON

**Comment by medensqui** [comment]
@thatoddmailbox ok

**Comment by thatoddmailbox** [comment]
@medensqui Try now.

**Comment by medensqui** [comment]
@thatoddmailbox nope

**Comment by medensqui** [comment]
@thatoddmailbox Also got this error
![screen shot 2015-10-27 at 9 26 27 am](https://cloud.githubusercontent.com/assets/12429395/10759275/d50590b8-7c8c-11e5-8821-5fc6a9d7bfc2.png)

**Comment by thatoddmailbox** [comment]
@medensqui I am still stupid and forgot to merge it. TRY NOW

**Comment by medensqui** [comment]
@thatoddmailbox YAY

**Comment by thatoddmailbox** [comment]
@medensqui YAAAAAAAY
