### ISSUE TITLE
Add weekend boxes for planner

### ISSUE THREAD

**Issue by thatoddmailbox** [PlanHubMe/PlanHub#78]

**Comment by medensqui** [comment]
@thatoddmailbox Yes pls.

**Comment by thatoddmailbox** [comment]
@medensqui Do you think it should be one for each subject, or, just big note boxes like the paper planner and daltonplanner.org

**Comment by medensqui** [comment]
@thatoddmailbox One each pls

**Comment by thatoddmailbox** [comment]
@medensqui Ok. Also should they count for HW view?

**Comment by medensqui** [comment]
@thatoddmailbox No, because they're more like planning boxes than anything

**Comment by thatoddmailbox** [comment]
Done!
