### ISSUE TITLE
DOES THE HEX THINGY WORK

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#81]
@thatoddmailbox @thatoddmailbox @thatoddmailbox

**Comment by thatoddmailbox** [comment]
@medensqui WHAT HEX THINGY

**Comment by medensqui** [comment]
@thatoddmailbox THE HEX SPINNY THINGY

**Comment by thatoddmailbox** [comment]
@medensqui HOW SHALL THIS BE TRIGGERED

**Comment by medensqui** [comment]
@thatoddmailbox THE KONAMI CODE OR A LITTLE HIDDEN BUTTON THAT WHEN YOU MOUSE OVER IT SHOWS

**Comment by willweinstein** [comment]
@thatoddmailbox why don't just have code search for a keyword like hex.spun();

**Comment by willbarkoff** [comment]
@thatoddmailbox @willweinstein @medensqui See #44

**Comment by willweinstein** [comment]
@nywillb what was so important that you couldn't walk up to the fourth floor

**Comment by willbarkoff** [comment]
@willweinstein Ummmm......

**Comment by willweinstein** [comment]
@medensqui is this josh?

**Comment by willweinstein** [comment]
@nywillb also, how do i join a repository? IM NOT FAMILIAR WITH GITHUB

**Comment by thatoddmailbox** [comment]
@nywillb @willweinstein @medensqui Closing, because this is the same as #44
