### ISSUE TITLE
RICKROLL - NOT AN "AWESOME APPLE PRESENTATION

### ISSUE THREAD

**Issue by medensqui** [PlanHubMe/PlanHub#86]
Check it out! And watch until the end

[rickroll](https://www.youtube.com/watch?v=BROWqjuTM0g) <- do not watch, rickroll!

**Comment by thatoddmailbox** [comment]
It's a rickroll!

**Comment by medensqui** [comment]
@thatoddmailbox DID YOU FALL FOR IT MWAHAHAHAHAHA

**Comment by thatoddmailbox** [comment]
@medensqui I have to make a rickroll blocking extension.

:wink:

**Comment by medensqui** [comment]
@thatoddmailbox SO YOU DID

Also make a GitHub Repo!

**Comment by thatoddmailbox** [comment]
@medensqui but how do you but something that doesn't exist in a GitHub repo?
